import { fileURLToPath } from 'node:url';
import tailwindcss from '@tailwindcss/vite';
import postcss from 'postcss';
import { build } from 'vite';

const source = fileURLToPath(new URL('../backend/src/routes/public/styles.css', import.meta.url));
const destination = Bun.file(
  new URL('../backend/src/routes/public/styles.gen.ts', import.meta.url),
);
const result = await build({
  configFile: false,
  root: fileURLToPath(new URL('..', import.meta.url)),
  logLevel: 'silent',
  plugins: [tailwindcss()],
  css: {
    postcss: {
      plugins: [
        {
          postcssPlugin: 'public-system-theme',
          Rule(rule) {
            // Public documents follow the system theme without a JavaScript theme controller.
            // Reuse the private app's dark tokens rather than maintaining another palette.
            if (rule.selector === '.dark') {
              rule.replaceWith(
                postcss
                  .atRule({ name: 'media', params: '(prefers-color-scheme: dark)' })
                  .append(rule.clone({ selector: ':root' })),
              );
            }
          },
        },
      ],
    },
  },
  build: {
    write: false,
    cssMinify: true,
    rollupOptions: { input: source },
  },
});
if (!('output' in result)) {
  throw new Error('Expected a single public stylesheet build');
}
const styles = result.output.filter(
  (file) => file.type === 'asset' && file.fileName.endsWith('.css'),
);
if (styles.length !== 1 || styles[0]?.type !== 'asset') {
  throw new Error('Expected exactly one compiled public stylesheet');
}
const generated = `// Generated by bun run generate:public-styles. Do not edit.\nexport const publicStyles = ${JSON.stringify(String(styles[0].source))};\n`;
if (Bun.argv.includes('--check')) {
  if (!(await destination.exists()) || (await destination.text()) !== generated) {
    throw new Error('Public styles are stale. Run bun run generate:public-styles.');
  }
} else {
  await Bun.write(destination, generated);
}
