// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `FindActiveApiKeyByName`. */
export interface IFindActiveApiKeyByNameResult {
    id: string;
}

/** Result of query `CreateApiKey`. */
export interface ICreateApiKeyResult {
    id: string | null;
}

/** Result of query `ListApiKeys`. */
export interface IListApiKeysResult {
    readableId: string;
    name: string;
    createdAt: string;
    revokedAt: string | null;
}

/** Result of query `RevokeApiKey`. */
export interface IRevokeApiKeyResult {
    id: string | null;
}

/** Result of query `AuthenticateApiKey`. */
export interface IAuthenticateApiKeyResult {
    keyId: string;
    ownerId: string;
    name: string;
}

/** Result of query `CreateAsset`. */
export interface ICreateAssetResult {
    id: string;
    ownerId: string;
    readableId: string;
    name: string;
    publicId: string | null;
    publishedAt: string | null;
    mediaType: string;
    extension: string | null;
    sizeBytes: number;
    storageKey: string;
    contentHash: string;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `ListAssets`. */
export interface IListAssetsResult {
    id: string;
    readableId: string;
    name: string;
    publicId: string | null;
    publishedAt: string | null;
    mediaType: string;
    extension: string | null;
    sizeBytes: number;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `CountAssets`. */
export interface ICountAssetsResult {
    total: number;
}

/** Result of query `FindAsset`. */
export interface IFindAssetResult {
    id: string;
    ownerId: string;
    readableId: string;
    name: string;
    publicId: string | null;
    publishedAt: string | null;
    mediaType: string;
    extension: string | null;
    sizeBytes: number;
    storageKey: string;
    contentHash: string;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `FindAssetChangeName`. */
export interface IFindAssetChangeNameResult {
    name: string;
}

/** Result of query `UpdateAssetName`. */
export interface IUpdateAssetNameResult {
    id: string;
    ownerId: string;
    readableId: string;
    name: string;
    publicId: string | null;
    publishedAt: string | null;
    mediaType: string;
    extension: string | null;
    sizeBytes: number;
    storageKey: string;
    contentHash: string;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `FindAssetArchiveTarget`. */
export interface IFindAssetArchiveTargetResult {
    id: string;
    name: string;
    archivedAt: string | null;
    publishedAt: string | null;
}

/** Result of query `RemoveAssetSearchDocument`. */
export interface IRemoveAssetSearchDocumentResult {
}

/** Result of query `ListAssetDepictedPeople`. */
export interface IListAssetDepictedPeopleResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    entityType: string | null;
    publicId: string | null;
    publishedAt: string | null;
    isSelf: number;
    source: "detected" | "confirmed";
}

/** Result of query `ListActivePageAssetUsages`. */
export interface IListActivePageAssetUsagesResult {
    id: string;
    readableId: string;
    title: string;
    excerpt: string;
    revisionNumber: number;
    temporalCoverage: string | null;
    publicId: string | null;
    publishedAt: string | null;
    publishedRevisionNumber: number | null;
    createdAt: string;
    updatedAt: string;
    presentation: "embed" | "attachment";
}

/** Result of query `ListActiveEntityImageAssetUsages`. */
export interface IListActiveEntityImageAssetUsagesResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    entityType: string | null;
    publicId: string | null;
    publishedAt: string | null;
    isSelf: number;
}

/** Result of query `ListActiveRecordAssetUsages`. */
export interface IListActiveRecordAssetUsagesResult {
    readableId: string;
    title: string;
    provider: string;
    kind: string;
    presentation: "embed" | "attachment";
}

/** Result of query `CreateEntity`. */
export interface ICreateEntityResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    entityType: string | null;
    publicId: string | null;
    publishedAt: string | null;
    isSelf: number;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `ListEntities`. */
export interface IListEntitiesResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    entityType: string | null;
    publicId: string | null;
    publishedAt: string | null;
    isSelf: number;
    createdAt: string;
    updatedAt: string;
    imagePublicId: string | null;
    imagePublishedAt: string | null;
    imageId: string | null;
    imageReadableId: string | null;
    imageName: string | null;
    imageMediaType: string | null;
    imageExtension: string | null;
    imageSizeBytes: number | null;
    imageCreatedAt: string | null;
    imageUpdatedAt: string | null;
}

/** Result of query `CountEntities`. */
export interface ICountEntitiesResult {
    total: number;
}

/** Result of query `FindEntity`. */
export interface IFindEntityResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    entityType: string | null;
    publicId: string | null;
    publishedAt: string | null;
    isSelf: number;
    createdAt: string;
    updatedAt: string;
    imagePublicId: string | null;
    imagePublishedAt: string | null;
    imageId: string | null;
    imageReadableId: string | null;
    imageName: string | null;
    imageMediaType: string | null;
    imageExtension: string | null;
    imageSizeBytes: number | null;
    imageCreatedAt: string | null;
    imageUpdatedAt: string | null;
}

/** Result of query `UpdateEntityIdentity`. */
export interface IUpdateEntityIdentityResult {
    id: string;
}

/** Result of query `FindEntityImagePublicationTarget`. */
export interface IFindEntityImagePublicationTargetResult {
    entityIsPublic: number;
    assetIsPublic: number;
}

/** Result of query `SetEntityImage`. */
export interface ISetEntityImageResult {
    entityId: string;
}

/** Result of query `RemoveEntityImage`. */
export interface IRemoveEntityImageResult {
    id: string;
}

/** Result of query `FindEntityArchiveTarget`. */
export interface IFindEntityArchiveTargetResult {
    id: string;
    archivedAt: string | null;
    isSelf: number;
    publishedAt: string | null;
}

/** Result of query `RemoveEntitySearchDocument`. */
export interface IRemoveEntitySearchDocumentResult {
}

/** Result of query `ListActiveEntityMentioningPages`. */
export interface IListActiveEntityMentioningPagesResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    temporalCoverage: string | null;
    publicId: string | null;
    publishedAt: string | null;
    publishedRevisionNumber: number | null;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `FaceChangePerson`. */
export interface IFaceChangePersonResult {
    name: string;
}

/** Result of query `InsertFaceResourceChange`. */
export interface IInsertFaceResourceChangeResult {
}

/** Result of query `ReadActivePortraitReference`. */
export interface IReadActivePortraitReferenceResult {
    faceId: string;
}

/** Result of query `ReadFaceObservations`. */
export interface IReadFaceObservationsResult {
    id: string;
    readableId: string;
    assetId: string;
    box: string;
    cropKey: string;
    detectionScore: number;
    analysisVersion: string;
    current: number;
    needsReview: number;
    embeddingSpace: string;
    embeddingRevision: string;
    vector: Uint8Array;
    protected: unknown;
}

/** Result of query `ReadFaceAnalysis`. */
export interface IReadFaceAnalysisResult {
    state: "processing" | "ready" | "failed";
    error: string | null;
    analysisVersion: string;
}

/** Result of query `ReadAssetFaceViews`. */
export interface IReadAssetFaceViewsResult {
    readableId: string;
    box: string;
    current: number;
    needsReview: number;
    decision: string | null;
    entityId: string | null;
    entityReadableId: string | null;
    name: string | null;
    description: string | null;
    entityType: string | null;
    publicId: string | null;
    publishedAt: string | null;
    selfEntityId: string | null;
    similarity: number | null;
}

/** Result of query `NextPendingFaceImage`. */
export interface INextPendingFaceImageResult {
    ownerId: string;
    readableId: string;
}

/** Result of query `FaceProcessingQueue`. */
export interface IFaceProcessingQueueResult {
    id: string;
    readableId: string;
    name: string;
    publicId: string | null;
    publishedAt: string | null;
    mediaType: string;
    extension: string | null;
    sizeBytes: number;
    createdAt: string;
    updatedAt: string;
    state: "queued" | "ready" | "failed" | "unsupported";
    error: string | null;
}

/** Result of query `FaceProcessingCounts`. */
export interface IFaceProcessingCountsResult {
    state: "queued" | "ready" | "failed" | "unsupported";
    count: unknown;
}

/** Result of query `CheckFaceAnalysisAttempt`. */
export interface ICheckFaceAnalysisAttemptResult {
    assetId: string;
}

/** Result of query `ListFaceReferences`. */
export interface IListFaceReferencesResult {
    entityId: string;
    faceId: string;
    assetId: string;
    embeddingSpace: string;
    embeddingRevision: string;
    vector: Uint8Array;
}

/** Result of query `FindPortraitReferenceCandidates`. */
export interface IFindPortraitReferenceCandidatesResult {
    faceId: string;
    decision: string | null;
    entityId: string | null;
}

/** Result of query `RetireReassignedFaceReferences`. */
export interface IRetireReassignedFaceReferencesResult {
    entityId: string;
}

/** Result of query `ReadPersonReferenceFace`. */
export interface IReadPersonReferenceFaceResult {
    readableId: string;
}

/** Result of query `FindFaceAnnotationTarget`. */
export interface IFindFaceAnnotationTargetResult {
    id: string;
    decision: string | null;
    entityId: string | null;
    name: string;
    readableId: string;
}

/** Result of query `RetireCorrectedFaceReferences`. */
export interface IRetireCorrectedFaceReferencesResult {
    entityId: string;
}

/** Result of query `ReadFaceThreshold`. */
export interface IReadFaceThresholdResult {
    threshold: number;
}

/** Result of query `FaceAssetBatch`. */
export interface IFaceAssetBatchResult {
    id: string;
    readableId: string;
    mediaType: string;
}

/** Result of query `ListPersonImages`. */
export interface IListPersonImagesResult {
    id: string;
    readableId: string;
    name: string;
    publicId: string | null;
    publishedAt: string | null;
    mediaType: string;
    extension: string | null;
    sizeBytes: number;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `PingDatabase`. */
export interface IPingDatabaseResult {
    value: number;
}

/** Result of query `ListResourceHistory`. */
export interface IListResourceHistoryResult {
    sequence: number;
    resourceType: string;
    readableId: string;
    name: string;
    action: string;
    message: string;
    clientName: string | null;
    details: string;
    pageRevisionNumber: number | null;
    createdAt: string;
    available: unknown;
}

/** Result of query `ListHypermediaNeighborhoods`. */
export interface IListHypermediaNeighborhoodsResult {
    rowType: "anchor" | "neighbor" | "relationship";
    sourceReadableId: string;
    sharedPageCount: number;
    position: number;
    id: string;
    readableId: string;
    name: string;
    description: string;
    entityType: string | null;
    publicId: string | null;
    publishedAt: string | null;
    isSelf: number;
    imagePublicId: string | null;
    imagePublishedAt: string | null;
    imageId: string | null;
    imageReadableId: string | null;
    imageName: string | null;
    imageMediaType: string | null;
    imageExtension: string | null;
    imageSizeBytes: number | null;
    imageCreatedAt: string | null;
    imageUpdatedAt: string | null;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `ListHypermediaPages`. */
export interface IListHypermediaPagesResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    temporalCoverage: string | null;
    publicId: string | null;
    publishedAt: string | null;
    publishedRevisionNumber: number | null;
    ongoingSort: number;
    latestSort: unknown | null;
    startSort: unknown | null;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `ListHypermediaPageEntities`. */
export interface IListHypermediaPageEntitiesResult {
    sourcePageReadableId: string;
    readableId: string;
}

/** Result of query `SearchHypermedia`. */
export interface ISearchHypermediaResult {
    total: number;
    resourceType: "entity" | "knowledge_page" | "asset" | "record";
    readableId: string;
    storageKey: string;
    contentHash: string;
    contentSizeBytes: number;
    entityId: string | null;
    entityName: string | null;
    entityDescription: string | null;
    entityPublicId: string | null;
    entityPublishedAt: string | null;
    entityType: string | null;
    isSelf: number;
    imagePublicId: string | null;
    imagePublishedAt: string | null;
    imageId: string | null;
    imageReadableId: string | null;
    imageName: string | null;
    imageMediaType: string | null;
    imageExtension: string | null;
    imageSizeBytes: number | null;
    imageCreatedAt: string | null;
    imageUpdatedAt: string | null;
    pageId: string | null;
    pageTitle: string | null;
    pageExcerpt: string | null;
    revisionNumber: number;
    temporalCoverage: string | null;
    pagePublicId: string | null;
    pagePublishedAt: string | null;
    publishedRevisionNumber: number | null;
    assetId: string | null;
    assetName: string | null;
    assetPublicId: string | null;
    assetPublishedAt: string | null;
    mediaType: string | null;
    assetExtension: string | null;
    assetSizeBytes: number | null;
    recordPublicId: string | null;
    recordPublishedAt: string | null;
    recordTitle: string | null;
    recordProvider: string | null;
    sourceCreatedAt: string | null;
    sourceUpdatedAt: string | null;
    recordKind: string | null;
    recordId: string | null;
    sourceUrl: string | null;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `FindKnowledgePageOwnerRevisionAuthor`. */
export interface IFindKnowledgePageOwnerRevisionAuthorResult {
    name: string;
}

/** Result of query `FindCurrentKnowledgePage`. */
export interface IFindCurrentKnowledgePageResult {
    id: string;
    ownerId: string;
    readableId: string;
    currentRevisionId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    temporalCoverage: string | null;
    publicId: string | null;
    publishedAt: string | null;
    publishedRevisionNumber: number | null;
    storageKey: string;
    contentHash: string;
    sizeBytes: number;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `ResolveRecordLink`. */
export interface IResolveRecordLinkResult {
    readable_id: string | null;
}

/** Result of query `ResolveEntityLink`. */
export interface IResolveEntityLinkResult {
    id: string;
}

/** Result of query `ResolvePageLink`. */
export interface IResolvePageLinkResult {
    id: string;
}

/** Result of query `ResolveAssetLink`. */
export interface IResolveAssetLinkResult {
    id: string;
}

/** Result of query `CreateKnowledgePage`. */
export interface ICreateKnowledgePageResult {
    id: string;
}

/** Result of query `ListKnowledgePages`. */
export interface IListKnowledgePagesResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    temporalCoverage: string | null;
    publicId: string | null;
    publishedAt: string | null;
    publishedRevisionNumber: number | null;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `CountKnowledgePages`. */
export interface ICountKnowledgePagesResult {
    total: number;
}

/** Result of query `ListKnowledgePagesByEntity`. */
export interface IListKnowledgePagesByEntityResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    temporalCoverage: string | null;
    publicId: string | null;
    publishedAt: string | null;
    publishedRevisionNumber: number | null;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `FindKnowledgePageComparisonRevisions`. */
export interface IFindKnowledgePageComparisonRevisionsResult {
    revisionNumber: number;
    temporalCoverage: string | null;
    storageKey: string;
    contentHash: string;
    sizeBytes: number;
}

/** Result of query `FindKnowledgePage`. */
export interface IFindKnowledgePageResult {
    id: string;
    ownerId: string;
    readableId: string;
    currentRevisionId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    temporalCoverage: string | null;
    publicId: string | null;
    publishedAt: string | null;
    publishedRevisionNumber: number | null;
    storageKey: string;
    contentHash: string;
    sizeBytes: number;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `FindKnowledgePageArchiveTarget`. */
export interface IFindKnowledgePageArchiveTargetResult {
    id: string;
    currentRevisionId: string;
    archivedAt: string | null;
    publishedAt: string | null;
}

/** Result of query `RemoveKnowledgePageSearchDocument`. */
export interface IRemoveKnowledgePageSearchDocumentResult {
}

/** Result of query `ListKnowledgePageMentions`. */
export interface IListKnowledgePageMentionsResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    entityType: string | null;
    publicId: string | null;
    publishedAt: string | null;
    isSelf: number;
    createdAt: string;
    updatedAt: string;
    imagePublicId: string | null;
    imagePublishedAt: string | null;
    imageId: string | null;
    imageReadableId: string | null;
    imageName: string | null;
    imageMediaType: string | null;
    imageExtension: string | null;
    imageSizeBytes: number | null;
    imageCreatedAt: string | null;
    imageUpdatedAt: string | null;
}

/** Result of query `ListKnowledgePageRevisions`. */
export interface IListKnowledgePageRevisionsResult {
    revisionNumber: number;
    title: string;
    temporalCoverage: string | null;
    authorKind: string;
    authorName: string | null;
    createdAt: string;
}

/** Result of query `ListActiveKnowledgePageReferrers`. */
export interface IListActiveKnowledgePageReferrersResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    temporalCoverage: string | null;
    publicId: string | null;
    publishedAt: string | null;
    publishedRevisionNumber: number | null;
    createdAt: string;
    updatedAt: string;
    fragment: string;
}

/** Result of query `ListKnowledgePageRecordReferences`. */
export interface IListKnowledgePageRecordReferencesResult {
    readableId: string;
    title: string | null;
    provider: string;
    kind: string;
    available: unknown;
}

/** Result of query `ListKnowledgePageReferences`. */
export interface IListKnowledgePageReferencesResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    temporalCoverage: string | null;
    publicId: string | null;
    publishedAt: string | null;
    publishedRevisionNumber: number | null;
    createdAt: string;
    updatedAt: string;
    fragment: string;
}

/** Result of query `ListKnowledgePageBacklinks`. */
export interface IListKnowledgePageBacklinksResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    temporalCoverage: string | null;
    publicId: string | null;
    publishedAt: string | null;
    publishedRevisionNumber: number | null;
    createdAt: string;
    updatedAt: string;
    fragment: string;
}

/** Result of query `ListKnowledgePageAssetUsages`. */
export interface IListKnowledgePageAssetUsagesResult {
    id: string;
    readableId: string;
    name: string;
    publicId: string | null;
    publishedAt: string | null;
    mediaType: string;
    extension: string | null;
    sizeBytes: number;
    createdAt: string;
    updatedAt: string;
    presentation: "embed" | "attachment";
}

/** Result of query `FindKnowledgeProfileOwner`. */
export interface IFindKnowledgeProfileOwnerResult {
    ownerId: string;
}

/** Result of query `CreateKnowledgeProfileEntity`. */
export interface ICreateKnowledgeProfileEntityResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    entityType: string | null;
    publicId: string | null;
    publishedAt: string | null;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `FindKnowledgeProfile`. */
export interface IFindKnowledgeProfileResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    entityType: string | null;
    publicId: string | null;
    publishedAt: string | null;
    isSelf: number;
    createdAt: string;
    updatedAt: string;
    imagePublicId: string | null;
    imagePublishedAt: string | null;
    imageId: string | null;
    imageReadableId: string | null;
    imageName: string | null;
    imageMediaType: string | null;
    imageExtension: string | null;
    imageSizeBytes: number | null;
    imageCreatedAt: string | null;
    imageUpdatedAt: string | null;
}

/** Result of query `FindMcpOAuthClient`. */
export interface IFindMcpOAuthClientResult {
    clientId: string;
    clientDiscoveryId: string | null;
    name: string | null;
}

/** Result of query `FindActiveMcpClientAuthorization`. */
export interface IFindActiveMcpClientAuthorizationResult {
    id: string;
    ownerId: string;
    name: string;
    oauthClientId: string;
    verifiedClientId: string | null;
    createdAt: string;
    updatedAt: string;
    archivedAt: string | null;
}

/** Result of query `FindActiveMcpClientAuthorizationById`. */
export interface IFindActiveMcpClientAuthorizationByIdResult {
    id: string;
    ownerId: string;
    name: string;
    oauthClientId: string;
    verifiedClientId: string | null;
    createdAt: string;
    updatedAt: string;
    archivedAt: string | null;
}

/** Result of query `ListMcpClientAuthorizations`. */
export interface IListMcpClientAuthorizationsResult {
    id: string;
    ownerId: string;
    name: string;
    oauthClientId: string;
    verifiedClientId: string | null;
    createdAt: string;
    updatedAt: string;
    archivedAt: string | null;
}

/** Result of query `RenameActiveMcpClientAuthorization`. */
export interface IRenameActiveMcpClientAuthorizationResult {
    id: string;
    ownerId: string;
    name: string;
    oauthClientId: string;
    verifiedClientId: string | null;
    createdAt: string;
    updatedAt: string;
    archivedAt: string | null;
}

/** Result of query `ReadOwnerRegistrationState`. */
export interface IReadOwnerRegistrationStateResult {
    ownerExists: number;
    passkeyExists: number;
}

/** Result of query `FindPublicHomepageId`. */
export interface IFindPublicHomepageIdResult {
    publicId: string;
}

/** Result of query `FindPublicEntity`. */
export interface IFindPublicEntityResult {
    name: string;
    description: string;
    entityType: string | null;
    modifiedAt: string;
    hasImage: number;
    imagePublicId: string | null;
    imageMediaType: string | null;
    pagePublicId: string | null;
    pageTitle: string | null;
}

/** Result of query `FindPublicPage`. */
export interface IFindPublicPageResult {
    title: string;
    modifiedAt: string;
    storageKey: string;
    contentHash: string;
    sizeBytes: number;
    kind: unknown | null;
    readableId: string | null;
    publicId: string | null;
    mediaType: string | null;
}

/** Result of query `FindPublicRecord`. */
export interface IFindPublicRecordResult {
    title: string;
    storageKey: string;
    contentHash: string;
    sizeBytes: number;
    kind: unknown | null;
    readableId: string | null;
    publicId: string | null;
    mediaType: string | null;
}

/** Result of query `FindPublicAsset`. */
export interface IFindPublicAssetResult {
    name: string;
    mediaType: string;
    extension: string | null;
    sizeBytes: number;
    contentHash: string;
    storageKey: string;
}

/** Result of query `FindPublicHomepage`. */
export interface IFindPublicHomepageResult {
    readableId: string;
    publicId: string;
    title: string;
}

/** Result of query `FindHomepageCandidate`. */
export interface IFindHomepageCandidateResult {
    id: string;
}

/** Result of query `ClearPublicHomepage`. */
export interface IClearPublicHomepageResult {
}

/** Result of query `SetPublicHomepage`. */
export interface ISetPublicHomepageResult {
}

/** Result of query `FindPendingPublicationApproval`. */
export interface IFindPendingPublicationApprovalResult {
    id: string;
    challenge: string;
    ownerId: string;
    resourceType: "page" | "entity" | "asset" | "record";
    readableId: string;
    action: "publish" | "unpublish";
    revisionNumber: number | null;
    expectedState: string;
    expiresAt: string;
}

/** Result of query `DeleteExpiredPublicationApprovals`. */
export interface IDeleteExpiredPublicationApprovalsResult {
}

/** Result of query `CreatePublicationApproval`. */
export interface ICreatePublicationApprovalResult {
    id: string;
}

/** Result of query `ListPublicationCredentials`. */
export interface IListPublicationCredentialsResult {
    id: string;
    credentialId: string;
    publicKey: string;
    counter: number;
    transports: string | null;
}

/** Result of query `ConsumePublicationApproval`. */
export interface IConsumePublicationApprovalResult {
}

/** Result of query `AdvancePublicationCredentialCounter`. */
export interface IAdvancePublicationCredentialCounterResult {
    id: string | null;
}

/** Result of query `FindPublicationReferringPages`. */
export interface IFindPublicationReferringPagesResult {
    readableId: string;
    name: string;
}

/** Result of query `FindPublicationReferringRecords`. */
export interface IFindPublicationReferringRecordsResult {
    readableId: string;
    name: string;
}

/** Result of query `FindPublicationPortraitEntities`. */
export interface IFindPublicationPortraitEntitiesResult {
    readableId: string;
    name: string;
}

/** Result of query `FindPagePublicationDependencies`. */
export interface IFindPagePublicationDependenciesResult {
    resourceType: "page" | "entity" | "asset" | "record";
    readableId: string;
    name: string;
    archivedAt: string | null;
    publishedAt: string | null;
    unavailable: unknown | null;
}

/** Result of query `FindRecordPublicationDependencies`. */
export interface IFindRecordPublicationDependenciesResult {
    readableId: string;
    name: string;
    archivedAt: string | null;
}

/** Result of query `FindPagePublicationStatus`. */
export interface IFindPagePublicationStatusResult {
    publicId: string | null;
    publishedAt: string | null;
    publishedRevisionNumber: number | null;
}

/** Result of query `FindEntityPublicationStatus`. */
export interface IFindEntityPublicationStatusResult {
    publicId: string | null;
    publishedAt: string | null;
}

/** Result of query `FindAssetPublicationStatus`. */
export interface IFindAssetPublicationStatusResult {
    publicId: string | null;
    publishedAt: string | null;
}

/** Result of query `FindRecordPublicationStatus`. */
export interface IFindRecordPublicationStatusResult {
    publicId: string | null;
    publishedAt: string | null;
}

/** Result of query `FindPagePublicationTarget`. */
export interface IFindPagePublicationTargetResult {
    id: string;
    readableId: string;
    archivedAt: string | null;
    name: string;
    revisionId: string | null;
    revisionNumber: number | null;
    excerpt: string | null;
    temporalCoverage: string | null;
    createdAt: string | null;
    contentHash: string | null;
    sizeBytes: number | null;
    publicId: string | null;
    publicHomepage: number | null;
    publishedAt: string | null;
    publishedRevisionId: string | null;
    publishedRevisionNumber: number | null;
}

/** Result of query `FindAssetPublicationTarget`. */
export interface IFindAssetPublicationTargetResult {
    id: string;
    readableId: string;
    name: string;
    mediaType: string;
    extension: string | null;
    sizeBytes: number;
    contentHash: string;
    archivedAt: string | null;
    publicId: string | null;
    publishedAt: string | null;
}

/** Result of query `FindEntityPublicationTarget`. */
export interface IFindEntityPublicationTargetResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    entityType: string | null;
    imageAssetId: string | null;
    imageReadableId: string | null;
    archivedAt: string | null;
    publicId: string | null;
    publishedAt: string | null;
}

/** Result of query `FindRecordPublicationTarget`. */
export interface IFindRecordPublicationTargetResult {
    id: string;
    readableId: string;
    name: string;
    contentHash: string;
    sizeBytes: number;
    archivedAt: string | null;
    publicId: string | null;
    publishedAt: string | null;
}

/** Result of query `SetRecordPublication`. */
export interface ISetRecordPublicationResult {
}

/** Result of query `SetPagePublication`. */
export interface ISetPagePublicationResult {
}

/** Result of query `SetEntityPublication`. */
export interface ISetEntityPublicationResult {
}

/** Result of query `SetAssetPublication`. */
export interface ISetAssetPublicationResult {
}

/** Result of query `InsertResourceChange`. */
export interface IInsertResourceChangeResult {
}

/** Result of query `AdvanceRecordSyncRevision`. */
export interface IAdvanceRecordSyncRevisionResult {
}

/** Result of query `WriteRecord`. */
export interface IWriteRecordResult {
}

/** Result of query `RemoveRecordAssetUsages`. */
export interface IRemoveRecordAssetUsagesResult {
}

/** Result of query `AddRecordAssetUsage`. */
export interface IAddRecordAssetUsageResult {
    assetId: string | null;
}

/** Result of query `FindCurrentRecord`. */
export interface IFindCurrentRecordResult {
    readableId: string | null;
    title: string | null;
    sourceUpdatedAt: string | null;
    sourceUrl: string | null;
    sourceCreatedAt: string | null;
    contentHash: string | null;
    deletedAt: string | null;
    syncRevision: number;
    publishedAt: string | null;
}

/** Result of query `FindPrivatePublicRecordAssets`. */
export interface IFindPrivatePublicRecordAssetsResult {
    readable_id: string;
}

/** Result of query `RemoveRecordSearchDocument`. */
export interface IRemoveRecordSearchDocumentResult {
}

/** Result of query `ListRecordResources`. */
export interface IListRecordResourcesResult {
    publicId: string | null;
    publishedAt: string | null;
    readableId: string;
    title: string;
    provider: string;
    kind: string;
    sourceId: string;
    sourceCreatedAt: string | null;
    sourceUpdatedAt: string | null;
    sourceUrl: string | null;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `RecordFilterOptions`. */
export interface IRecordFilterOptionsResult {
    provider: string;
    kind: string;
}

/** Result of query `FindRecordResource`. */
export interface IFindRecordResourceResult {
    publicId: string | null;
    publishedAt: string | null;
    title: string;
    provider: string;
    sourceCreatedAt: string | null;
    sourceUpdatedAt: string | null;
    sourceUrl: string | null;
    readableId: string;
    kind: string;
    sourceId: string;
    storageKey: string;
    contentHash: string;
    sizeBytes: number;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `ListRecordBacklinks`. */
export interface IListRecordBacklinksResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    temporalCoverage: string | null;
    publicId: string | null;
    publishedAt: string | null;
    publishedRevisionNumber: number | null;
    createdAt: string;
    updatedAt: string;
}

export interface Queries {
    FindActiveApiKeyByName: IFindActiveApiKeyByNameResult;
    CreateApiKey: ICreateApiKeyResult;
    ListApiKeys: IListApiKeysResult;
    RevokeApiKey: IRevokeApiKeyResult;
    AuthenticateApiKey: IAuthenticateApiKeyResult;
    CreateAsset: ICreateAssetResult;
    ListAssets: IListAssetsResult;
    CountAssets: ICountAssetsResult;
    FindAsset: IFindAssetResult;
    FindAssetChangeName: IFindAssetChangeNameResult;
    UpdateAssetName: IUpdateAssetNameResult;
    FindAssetArchiveTarget: IFindAssetArchiveTargetResult;
    RemoveAssetSearchDocument: IRemoveAssetSearchDocumentResult;
    ListAssetDepictedPeople: IListAssetDepictedPeopleResult;
    ListActivePageAssetUsages: IListActivePageAssetUsagesResult;
    ListActiveEntityImageAssetUsages: IListActiveEntityImageAssetUsagesResult;
    ListActiveRecordAssetUsages: IListActiveRecordAssetUsagesResult;
    CreateEntity: ICreateEntityResult;
    ListEntities: IListEntitiesResult;
    CountEntities: ICountEntitiesResult;
    FindEntity: IFindEntityResult;
    UpdateEntityIdentity: IUpdateEntityIdentityResult;
    FindEntityImagePublicationTarget: IFindEntityImagePublicationTargetResult;
    SetEntityImage: ISetEntityImageResult;
    RemoveEntityImage: IRemoveEntityImageResult;
    FindEntityArchiveTarget: IFindEntityArchiveTargetResult;
    RemoveEntitySearchDocument: IRemoveEntitySearchDocumentResult;
    ListActiveEntityMentioningPages: IListActiveEntityMentioningPagesResult;
    FaceChangePerson: IFaceChangePersonResult;
    InsertFaceResourceChange: IInsertFaceResourceChangeResult;
    ReadActivePortraitReference: IReadActivePortraitReferenceResult;
    ReadFaceObservations: IReadFaceObservationsResult;
    ReadFaceAnalysis: IReadFaceAnalysisResult;
    ReadAssetFaceViews: IReadAssetFaceViewsResult;
    NextPendingFaceImage: INextPendingFaceImageResult;
    FaceProcessingQueue: IFaceProcessingQueueResult;
    FaceProcessingCounts: IFaceProcessingCountsResult;
    CheckFaceAnalysisAttempt: ICheckFaceAnalysisAttemptResult;
    ListFaceReferences: IListFaceReferencesResult;
    FindPortraitReferenceCandidates: IFindPortraitReferenceCandidatesResult;
    RetireReassignedFaceReferences: IRetireReassignedFaceReferencesResult;
    ReadPersonReferenceFace: IReadPersonReferenceFaceResult;
    FindFaceAnnotationTarget: IFindFaceAnnotationTargetResult;
    RetireCorrectedFaceReferences: IRetireCorrectedFaceReferencesResult;
    ReadFaceThreshold: IReadFaceThresholdResult;
    FaceAssetBatch: IFaceAssetBatchResult;
    ListPersonImages: IListPersonImagesResult;
    PingDatabase: IPingDatabaseResult;
    ListResourceHistory: IListResourceHistoryResult;
    ListHypermediaNeighborhoods: IListHypermediaNeighborhoodsResult;
    ListHypermediaPages: IListHypermediaPagesResult;
    ListHypermediaPageEntities: IListHypermediaPageEntitiesResult;
    SearchHypermedia: ISearchHypermediaResult;
    FindKnowledgePageOwnerRevisionAuthor: IFindKnowledgePageOwnerRevisionAuthorResult;
    FindCurrentKnowledgePage: IFindCurrentKnowledgePageResult;
    ResolveRecordLink: IResolveRecordLinkResult;
    ResolveEntityLink: IResolveEntityLinkResult;
    ResolvePageLink: IResolvePageLinkResult;
    ResolveAssetLink: IResolveAssetLinkResult;
    CreateKnowledgePage: ICreateKnowledgePageResult;
    ListKnowledgePages: IListKnowledgePagesResult;
    CountKnowledgePages: ICountKnowledgePagesResult;
    ListKnowledgePagesByEntity: IListKnowledgePagesByEntityResult;
    FindKnowledgePageComparisonRevisions: IFindKnowledgePageComparisonRevisionsResult;
    FindKnowledgePage: IFindKnowledgePageResult;
    FindKnowledgePageArchiveTarget: IFindKnowledgePageArchiveTargetResult;
    RemoveKnowledgePageSearchDocument: IRemoveKnowledgePageSearchDocumentResult;
    ListKnowledgePageMentions: IListKnowledgePageMentionsResult;
    ListKnowledgePageRevisions: IListKnowledgePageRevisionsResult;
    ListActiveKnowledgePageReferrers: IListActiveKnowledgePageReferrersResult;
    ListKnowledgePageRecordReferences: IListKnowledgePageRecordReferencesResult;
    ListKnowledgePageReferences: IListKnowledgePageReferencesResult;
    ListKnowledgePageBacklinks: IListKnowledgePageBacklinksResult;
    ListKnowledgePageAssetUsages: IListKnowledgePageAssetUsagesResult;
    FindKnowledgeProfileOwner: IFindKnowledgeProfileOwnerResult;
    CreateKnowledgeProfileEntity: ICreateKnowledgeProfileEntityResult;
    FindKnowledgeProfile: IFindKnowledgeProfileResult;
    FindMcpOAuthClient: IFindMcpOAuthClientResult;
    FindActiveMcpClientAuthorization: IFindActiveMcpClientAuthorizationResult;
    FindActiveMcpClientAuthorizationById: IFindActiveMcpClientAuthorizationByIdResult;
    ListMcpClientAuthorizations: IListMcpClientAuthorizationsResult;
    RenameActiveMcpClientAuthorization: IRenameActiveMcpClientAuthorizationResult;
    ReadOwnerRegistrationState: IReadOwnerRegistrationStateResult;
    FindPublicHomepageId: IFindPublicHomepageIdResult;
    FindPublicEntity: IFindPublicEntityResult;
    FindPublicPage: IFindPublicPageResult;
    FindPublicRecord: IFindPublicRecordResult;
    FindPublicAsset: IFindPublicAssetResult;
    FindPublicHomepage: IFindPublicHomepageResult;
    FindHomepageCandidate: IFindHomepageCandidateResult;
    ClearPublicHomepage: IClearPublicHomepageResult;
    SetPublicHomepage: ISetPublicHomepageResult;
    FindPendingPublicationApproval: IFindPendingPublicationApprovalResult;
    DeleteExpiredPublicationApprovals: IDeleteExpiredPublicationApprovalsResult;
    CreatePublicationApproval: ICreatePublicationApprovalResult;
    ListPublicationCredentials: IListPublicationCredentialsResult;
    ConsumePublicationApproval: IConsumePublicationApprovalResult;
    AdvancePublicationCredentialCounter: IAdvancePublicationCredentialCounterResult;
    FindPublicationReferringPages: IFindPublicationReferringPagesResult;
    FindPublicationReferringRecords: IFindPublicationReferringRecordsResult;
    FindPublicationPortraitEntities: IFindPublicationPortraitEntitiesResult;
    FindPagePublicationDependencies: IFindPagePublicationDependenciesResult;
    FindRecordPublicationDependencies: IFindRecordPublicationDependenciesResult;
    FindPagePublicationStatus: IFindPagePublicationStatusResult;
    FindEntityPublicationStatus: IFindEntityPublicationStatusResult;
    FindAssetPublicationStatus: IFindAssetPublicationStatusResult;
    FindRecordPublicationStatus: IFindRecordPublicationStatusResult;
    FindPagePublicationTarget: IFindPagePublicationTargetResult;
    FindAssetPublicationTarget: IFindAssetPublicationTargetResult;
    FindEntityPublicationTarget: IFindEntityPublicationTargetResult;
    FindRecordPublicationTarget: IFindRecordPublicationTargetResult;
    SetRecordPublication: ISetRecordPublicationResult;
    SetPagePublication: ISetPagePublicationResult;
    SetEntityPublication: ISetEntityPublicationResult;
    SetAssetPublication: ISetAssetPublicationResult;
    InsertResourceChange: IInsertResourceChangeResult;
    AdvanceRecordSyncRevision: IAdvanceRecordSyncRevisionResult;
    WriteRecord: IWriteRecordResult;
    RemoveRecordAssetUsages: IRemoveRecordAssetUsagesResult;
    AddRecordAssetUsage: IAddRecordAssetUsageResult;
    FindCurrentRecord: IFindCurrentRecordResult;
    FindPrivatePublicRecordAssets: IFindPrivatePublicRecordAssetsResult;
    RemoveRecordSearchDocument: IRemoveRecordSearchDocumentResult;
    ListRecordResources: IListRecordResourcesResult;
    RecordFilterOptions: IRecordFilterOptionsResult;
    FindRecordResource: IFindRecordResourceResult;
    ListRecordBacklinks: IListRecordBacklinksResult;
}

declare module "@ilbertt/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
}

export {};
