/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAssetsRouteImport } from './routes/app.assets'
import { Route as AppEntitiesRouteImport } from './routes/app.entities'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppLoginRouteImport } from './routes/app.login'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppPagesRouteImport } from './routes/app.pages'
import { Route as AppRecordsRouteImport } from './routes/app.records'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSetupRouteImport } from './routes/app.setup'
import { Route as AppSyncsRouteImport } from './routes/app.syncs'
import { Route as AppAssetsIndexRouteImport } from './routes/app.assets.index'
import { Route as AppAssetsIdRouteImport } from './routes/app.assets.$id'
import { Route as AppAssetsNewRouteImport } from './routes/app.assets.new'
import { Route as AppEntitiesIndexRouteImport } from './routes/app.entities.index'
import { Route as AppEntitiesIdRouteImport } from './routes/app.entities.$id'
import { Route as AppEntitiesNewRouteImport } from './routes/app.entities.new'
import { Route as AppMcpAuthorizeRouteImport } from './routes/app.mcp.authorize'
import { Route as AppPagesIndexRouteImport } from './routes/app.pages.index'
import { Route as AppPagesIdRouteImport } from './routes/app.pages.$id'
import { Route as AppPagesNewRouteImport } from './routes/app.pages.new'
import { Route as AppRecordsIndexRouteImport } from './routes/app.records.index'
import { Route as AppRecordsIdRouteImport } from './routes/app.records.$id'
import { Route as AppSettingsIndexRouteImport } from './routes/app.settings.index'
import { Route as AppSettingsApiKeysRouteImport } from './routes/app.settings.api-keys'
import { Route as AppSettingsFacesRouteImport } from './routes/app.settings.faces'
import { Route as AppSettingsPasskeysRouteImport } from './routes/app.settings.passkeys'
import { Route as AppSettingsPluginsRouteImport } from './routes/app.settings.plugins'
import { Route as AppSettingsPublicSiteRouteImport } from './routes/app.settings.public-site'
import { Route as AppSyncsIndexRouteImport } from './routes/app.syncs.index'
import { Route as AppSyncsProviderIdRouteImport } from './routes/app.syncs.$providerId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppEntitiesRoute = AppEntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppPagesRoute = AppPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppSyncsRoute = AppSyncsRouteImport.update({
  id: '/syncs',
  path: '/syncs',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAssetsRoute,
} as any)
const AppAssetsIdRoute = AppAssetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAssetsRoute,
} as any)
const AppAssetsNewRoute = AppAssetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppAssetsRoute,
} as any)
const AppEntitiesIndexRoute = AppEntitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEntitiesRoute,
} as any)
const AppEntitiesIdRoute = AppEntitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEntitiesRoute,
} as any)
const AppEntitiesNewRoute = AppEntitiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppEntitiesRoute,
} as any)
const AppMcpAuthorizeRoute = AppMcpAuthorizeRouteImport.update({
  id: '/mcp/authorize',
  path: '/mcp/authorize',
  getParentRoute: () => AppRoute,
} as any)
const AppPagesIndexRoute = AppPagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPagesRoute,
} as any)
const AppPagesIdRoute = AppPagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPagesRoute,
} as any)
const AppPagesNewRoute = AppPagesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPagesRoute,
} as any)
const AppRecordsIndexRoute = AppRecordsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRecordsRoute,
} as any)
const AppRecordsIdRoute = AppRecordsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRecordsRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsApiKeysRoute = AppSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsFacesRoute = AppSettingsFacesRouteImport.update({
  id: '/faces',
  path: '/faces',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPasskeysRoute = AppSettingsPasskeysRouteImport.update({
  id: '/passkeys',
  path: '/passkeys',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPluginsRoute = AppSettingsPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPublicSiteRoute = AppSettingsPublicSiteRouteImport.update({
  id: '/public-site',
  path: '/public-site',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSyncsIndexRoute = AppSyncsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSyncsRoute,
} as any)
const AppSyncsProviderIdRoute = AppSyncsProviderIdRouteImport.update({
  id: '/$providerId',
  path: '/$providerId',
  getParentRoute: () => AppSyncsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteWithChildren
  '/app/assets': typeof AppAssetsRouteWithChildren
  '/app/entities': typeof AppEntitiesRouteWithChildren
  '/app/history': typeof AppHistoryRoute
  '/app/login': typeof AppLoginRoute
  '/app/map': typeof AppMapRoute
  '/app/pages': typeof AppPagesRouteWithChildren
  '/app/records': typeof AppRecordsRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/setup': typeof AppSetupRoute
  '/app/syncs': typeof AppSyncsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/assets/$id': typeof AppAssetsIdRoute
  '/app/assets/new': typeof AppAssetsNewRoute
  '/app/entities/$id': typeof AppEntitiesIdRoute
  '/app/entities/new': typeof AppEntitiesNewRoute
  '/app/mcp/authorize': typeof AppMcpAuthorizeRoute
  '/app/pages/$id': typeof AppPagesIdRoute
  '/app/pages/new': typeof AppPagesNewRoute
  '/app/records/$id': typeof AppRecordsIdRoute
  '/app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/app/settings/faces': typeof AppSettingsFacesRoute
  '/app/settings/passkeys': typeof AppSettingsPasskeysRoute
  '/app/settings/plugins': typeof AppSettingsPluginsRoute
  '/app/settings/public-site': typeof AppSettingsPublicSiteRoute
  '/app/syncs/$providerId': typeof AppSyncsProviderIdRoute
  '/app/assets/': typeof AppAssetsIndexRoute
  '/app/entities/': typeof AppEntitiesIndexRoute
  '/app/pages/': typeof AppPagesIndexRoute
  '/app/records/': typeof AppRecordsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/syncs/': typeof AppSyncsIndexRoute
}
export interface FileRoutesByTo {
  '/app/history': typeof AppHistoryRoute
  '/app/login': typeof AppLoginRoute
  '/app/map': typeof AppMapRoute
  '/app/setup': typeof AppSetupRoute
  '/app': typeof AppIndexRoute
  '/app/assets/$id': typeof AppAssetsIdRoute
  '/app/assets/new': typeof AppAssetsNewRoute
  '/app/entities/$id': typeof AppEntitiesIdRoute
  '/app/entities/new': typeof AppEntitiesNewRoute
  '/app/mcp/authorize': typeof AppMcpAuthorizeRoute
  '/app/pages/$id': typeof AppPagesIdRoute
  '/app/pages/new': typeof AppPagesNewRoute
  '/app/records/$id': typeof AppRecordsIdRoute
  '/app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/app/settings/faces': typeof AppSettingsFacesRoute
  '/app/settings/passkeys': typeof AppSettingsPasskeysRoute
  '/app/settings/plugins': typeof AppSettingsPluginsRoute
  '/app/settings/public-site': typeof AppSettingsPublicSiteRoute
  '/app/syncs/$providerId': typeof AppSyncsProviderIdRoute
  '/app/assets': typeof AppAssetsIndexRoute
  '/app/entities': typeof AppEntitiesIndexRoute
  '/app/pages': typeof AppPagesIndexRoute
  '/app/records': typeof AppRecordsIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/syncs': typeof AppSyncsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteWithChildren
  '/app/assets': typeof AppAssetsRouteWithChildren
  '/app/entities': typeof AppEntitiesRouteWithChildren
  '/app/history': typeof AppHistoryRoute
  '/app/login': typeof AppLoginRoute
  '/app/map': typeof AppMapRoute
  '/app/pages': typeof AppPagesRouteWithChildren
  '/app/records': typeof AppRecordsRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/setup': typeof AppSetupRoute
  '/app/syncs': typeof AppSyncsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/assets/$id': typeof AppAssetsIdRoute
  '/app/assets/new': typeof AppAssetsNewRoute
  '/app/entities/$id': typeof AppEntitiesIdRoute
  '/app/entities/new': typeof AppEntitiesNewRoute
  '/app/mcp/authorize': typeof AppMcpAuthorizeRoute
  '/app/pages/$id': typeof AppPagesIdRoute
  '/app/pages/new': typeof AppPagesNewRoute
  '/app/records/$id': typeof AppRecordsIdRoute
  '/app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/app/settings/faces': typeof AppSettingsFacesRoute
  '/app/settings/passkeys': typeof AppSettingsPasskeysRoute
  '/app/settings/plugins': typeof AppSettingsPluginsRoute
  '/app/settings/public-site': typeof AppSettingsPublicSiteRoute
  '/app/syncs/$providerId': typeof AppSyncsProviderIdRoute
  '/app/assets/': typeof AppAssetsIndexRoute
  '/app/entities/': typeof AppEntitiesIndexRoute
  '/app/pages/': typeof AppPagesIndexRoute
  '/app/records/': typeof AppRecordsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/syncs/': typeof AppSyncsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/app/assets'
    | '/app/entities'
    | '/app/history'
    | '/app/login'
    | '/app/map'
    | '/app/pages'
    | '/app/records'
    | '/app/settings'
    | '/app/setup'
    | '/app/syncs'
    | '/app/'
    | '/app/assets/$id'
    | '/app/assets/new'
    | '/app/entities/$id'
    | '/app/entities/new'
    | '/app/mcp/authorize'
    | '/app/pages/$id'
    | '/app/pages/new'
    | '/app/records/$id'
    | '/app/settings/api-keys'
    | '/app/settings/faces'
    | '/app/settings/passkeys'
    | '/app/settings/plugins'
    | '/app/settings/public-site'
    | '/app/syncs/$providerId'
    | '/app/assets/'
    | '/app/entities/'
    | '/app/pages/'
    | '/app/records/'
    | '/app/settings/'
    | '/app/syncs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app/history'
    | '/app/login'
    | '/app/map'
    | '/app/setup'
    | '/app'
    | '/app/assets/$id'
    | '/app/assets/new'
    | '/app/entities/$id'
    | '/app/entities/new'
    | '/app/mcp/authorize'
    | '/app/pages/$id'
    | '/app/pages/new'
    | '/app/records/$id'
    | '/app/settings/api-keys'
    | '/app/settings/faces'
    | '/app/settings/passkeys'
    | '/app/settings/plugins'
    | '/app/settings/public-site'
    | '/app/syncs/$providerId'
    | '/app/assets'
    | '/app/entities'
    | '/app/pages'
    | '/app/records'
    | '/app/settings'
    | '/app/syncs'
  id:
    | '__root__'
    | '/app'
    | '/app/assets'
    | '/app/entities'
    | '/app/history'
    | '/app/login'
    | '/app/map'
    | '/app/pages'
    | '/app/records'
    | '/app/settings'
    | '/app/setup'
    | '/app/syncs'
    | '/app/'
    | '/app/assets/$id'
    | '/app/assets/new'
    | '/app/entities/$id'
    | '/app/entities/new'
    | '/app/mcp/authorize'
    | '/app/pages/$id'
    | '/app/pages/new'
    | '/app/records/$id'
    | '/app/settings/api-keys'
    | '/app/settings/faces'
    | '/app/settings/passkeys'
    | '/app/settings/plugins'
    | '/app/settings/public-site'
    | '/app/syncs/$providerId'
    | '/app/assets/'
    | '/app/entities/'
    | '/app/pages/'
    | '/app/records/'
    | '/app/settings/'
    | '/app/syncs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets': {
      id: '/app/assets'
      path: '/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/entities': {
      id: '/app/entities'
      path: '/entities'
      fullPath: '/app/entities'
      preLoaderRoute: typeof AppEntitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pages': {
      id: '/app/pages'
      path: '/pages'
      fullPath: '/app/pages'
      preLoaderRoute: typeof AppPagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/records': {
      id: '/app/records'
      path: '/records'
      fullPath: '/app/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/setup': {
      id: '/app/setup'
      path: '/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/syncs': {
      id: '/app/syncs'
      path: '/syncs'
      fullPath: '/app/syncs'
      preLoaderRoute: typeof AppSyncsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets/': {
      id: '/app/assets/'
      path: '/'
      fullPath: '/app/assets/'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppAssetsRoute
    }
    '/app/assets/$id': {
      id: '/app/assets/$id'
      path: '/$id'
      fullPath: '/app/assets/$id'
      preLoaderRoute: typeof AppAssetsIdRouteImport
      parentRoute: typeof AppAssetsRoute
    }
    '/app/assets/new': {
      id: '/app/assets/new'
      path: '/new'
      fullPath: '/app/assets/new'
      preLoaderRoute: typeof AppAssetsNewRouteImport
      parentRoute: typeof AppAssetsRoute
    }
    '/app/entities/': {
      id: '/app/entities/'
      path: '/'
      fullPath: '/app/entities/'
      preLoaderRoute: typeof AppEntitiesIndexRouteImport
      parentRoute: typeof AppEntitiesRoute
    }
    '/app/entities/$id': {
      id: '/app/entities/$id'
      path: '/$id'
      fullPath: '/app/entities/$id'
      preLoaderRoute: typeof AppEntitiesIdRouteImport
      parentRoute: typeof AppEntitiesRoute
    }
    '/app/entities/new': {
      id: '/app/entities/new'
      path: '/new'
      fullPath: '/app/entities/new'
      preLoaderRoute: typeof AppEntitiesNewRouteImport
      parentRoute: typeof AppEntitiesRoute
    }
    '/app/mcp/authorize': {
      id: '/app/mcp/authorize'
      path: '/mcp/authorize'
      fullPath: '/app/mcp/authorize'
      preLoaderRoute: typeof AppMcpAuthorizeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pages/': {
      id: '/app/pages/'
      path: '/'
      fullPath: '/app/pages/'
      preLoaderRoute: typeof AppPagesIndexRouteImport
      parentRoute: typeof AppPagesRoute
    }
    '/app/pages/$id': {
      id: '/app/pages/$id'
      path: '/$id'
      fullPath: '/app/pages/$id'
      preLoaderRoute: typeof AppPagesIdRouteImport
      parentRoute: typeof AppPagesRoute
    }
    '/app/pages/new': {
      id: '/app/pages/new'
      path: '/new'
      fullPath: '/app/pages/new'
      preLoaderRoute: typeof AppPagesNewRouteImport
      parentRoute: typeof AppPagesRoute
    }
    '/app/records/': {
      id: '/app/records/'
      path: '/'
      fullPath: '/app/records/'
      preLoaderRoute: typeof AppRecordsIndexRouteImport
      parentRoute: typeof AppRecordsRoute
    }
    '/app/records/$id': {
      id: '/app/records/$id'
      path: '/$id'
      fullPath: '/app/records/$id'
      preLoaderRoute: typeof AppRecordsIdRouteImport
      parentRoute: typeof AppRecordsRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/api-keys': {
      id: '/app/settings/api-keys'
      path: '/api-keys'
      fullPath: '/app/settings/api-keys'
      preLoaderRoute: typeof AppSettingsApiKeysRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/faces': {
      id: '/app/settings/faces'
      path: '/faces'
      fullPath: '/app/settings/faces'
      preLoaderRoute: typeof AppSettingsFacesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/passkeys': {
      id: '/app/settings/passkeys'
      path: '/passkeys'
      fullPath: '/app/settings/passkeys'
      preLoaderRoute: typeof AppSettingsPasskeysRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/plugins': {
      id: '/app/settings/plugins'
      path: '/plugins'
      fullPath: '/app/settings/plugins'
      preLoaderRoute: typeof AppSettingsPluginsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/public-site': {
      id: '/app/settings/public-site'
      path: '/public-site'
      fullPath: '/app/settings/public-site'
      preLoaderRoute: typeof AppSettingsPublicSiteRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/syncs/': {
      id: '/app/syncs/'
      path: '/'
      fullPath: '/app/syncs/'
      preLoaderRoute: typeof AppSyncsIndexRouteImport
      parentRoute: typeof AppSyncsRoute
    }
    '/app/syncs/$providerId': {
      id: '/app/syncs/$providerId'
      path: '/$providerId'
      fullPath: '/app/syncs/$providerId'
      preLoaderRoute: typeof AppSyncsProviderIdRouteImport
      parentRoute: typeof AppSyncsRoute
    }
  }
}

interface AppAssetsRouteChildren {
  AppAssetsIdRoute: typeof AppAssetsIdRoute
  AppAssetsNewRoute: typeof AppAssetsNewRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
}

const AppAssetsRouteChildren: AppAssetsRouteChildren = {
  AppAssetsIdRoute: AppAssetsIdRoute,
  AppAssetsNewRoute: AppAssetsNewRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
}

const AppAssetsRouteWithChildren = AppAssetsRoute._addFileChildren(
  AppAssetsRouteChildren,
)

interface AppEntitiesRouteChildren {
  AppEntitiesIdRoute: typeof AppEntitiesIdRoute
  AppEntitiesNewRoute: typeof AppEntitiesNewRoute
  AppEntitiesIndexRoute: typeof AppEntitiesIndexRoute
}

const AppEntitiesRouteChildren: AppEntitiesRouteChildren = {
  AppEntitiesIdRoute: AppEntitiesIdRoute,
  AppEntitiesNewRoute: AppEntitiesNewRoute,
  AppEntitiesIndexRoute: AppEntitiesIndexRoute,
}

const AppEntitiesRouteWithChildren = AppEntitiesRoute._addFileChildren(
  AppEntitiesRouteChildren,
)

interface AppPagesRouteChildren {
  AppPagesIdRoute: typeof AppPagesIdRoute
  AppPagesNewRoute: typeof AppPagesNewRoute
  AppPagesIndexRoute: typeof AppPagesIndexRoute
}

const AppPagesRouteChildren: AppPagesRouteChildren = {
  AppPagesIdRoute: AppPagesIdRoute,
  AppPagesNewRoute: AppPagesNewRoute,
  AppPagesIndexRoute: AppPagesIndexRoute,
}

const AppPagesRouteWithChildren = AppPagesRoute._addFileChildren(
  AppPagesRouteChildren,
)

interface AppRecordsRouteChildren {
  AppRecordsIdRoute: typeof AppRecordsIdRoute
  AppRecordsIndexRoute: typeof AppRecordsIndexRoute
}

const AppRecordsRouteChildren: AppRecordsRouteChildren = {
  AppRecordsIdRoute: AppRecordsIdRoute,
  AppRecordsIndexRoute: AppRecordsIndexRoute,
}

const AppRecordsRouteWithChildren = AppRecordsRoute._addFileChildren(
  AppRecordsRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsApiKeysRoute: typeof AppSettingsApiKeysRoute
  AppSettingsFacesRoute: typeof AppSettingsFacesRoute
  AppSettingsPasskeysRoute: typeof AppSettingsPasskeysRoute
  AppSettingsPluginsRoute: typeof AppSettingsPluginsRoute
  AppSettingsPublicSiteRoute: typeof AppSettingsPublicSiteRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsApiKeysRoute: AppSettingsApiKeysRoute,
  AppSettingsFacesRoute: AppSettingsFacesRoute,
  AppSettingsPasskeysRoute: AppSettingsPasskeysRoute,
  AppSettingsPluginsRoute: AppSettingsPluginsRoute,
  AppSettingsPublicSiteRoute: AppSettingsPublicSiteRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppSyncsRouteChildren {
  AppSyncsProviderIdRoute: typeof AppSyncsProviderIdRoute
  AppSyncsIndexRoute: typeof AppSyncsIndexRoute
}

const AppSyncsRouteChildren: AppSyncsRouteChildren = {
  AppSyncsProviderIdRoute: AppSyncsProviderIdRoute,
  AppSyncsIndexRoute: AppSyncsIndexRoute,
}

const AppSyncsRouteWithChildren = AppSyncsRoute._addFileChildren(
  AppSyncsRouteChildren,
)

interface AppRouteChildren {
  AppAssetsRoute: typeof AppAssetsRouteWithChildren
  AppEntitiesRoute: typeof AppEntitiesRouteWithChildren
  AppHistoryRoute: typeof AppHistoryRoute
  AppLoginRoute: typeof AppLoginRoute
  AppMapRoute: typeof AppMapRoute
  AppPagesRoute: typeof AppPagesRouteWithChildren
  AppRecordsRoute: typeof AppRecordsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSetupRoute: typeof AppSetupRoute
  AppSyncsRoute: typeof AppSyncsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppMcpAuthorizeRoute: typeof AppMcpAuthorizeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssetsRoute: AppAssetsRouteWithChildren,
  AppEntitiesRoute: AppEntitiesRouteWithChildren,
  AppHistoryRoute: AppHistoryRoute,
  AppLoginRoute: AppLoginRoute,
  AppMapRoute: AppMapRoute,
  AppPagesRoute: AppPagesRouteWithChildren,
  AppRecordsRoute: AppRecordsRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSetupRoute: AppSetupRoute,
  AppSyncsRoute: AppSyncsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppMcpAuthorizeRoute: AppMcpAuthorizeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
