// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `CreateAsset`. */
export interface ICreateAssetResult {
    id: string;
    ownerId: string;
    readableId: string;
    name: string;
    mediaType: string;
    extension: string | null;
    sizeBytes: number;
    storageKey: string;
    contentHash: string;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `SearchAssets`. */
export interface ISearchAssetsResult {
    id: string;
    readableId: string;
    name: string;
    mediaType: string;
    extension: string | null;
    sizeBytes: number;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `ListAssets`. */
export interface IListAssetsResult {
    id: string;
    readableId: string;
    name: string;
    mediaType: string;
    extension: string | null;
    sizeBytes: number;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `CountSearchedAssets`. */
export interface ICountSearchedAssetsResult {
    total: number;
}

/** Result of query `CountAssets`. */
export interface ICountAssetsResult {
    total: number;
}

/** Result of query `FindAsset`. */
export interface IFindAssetResult {
    id: string;
    ownerId: string;
    readableId: string;
    name: string;
    mediaType: string;
    extension: string | null;
    sizeBytes: number;
    storageKey: string;
    contentHash: string;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `UpdateAssetName`. */
export interface IUpdateAssetNameResult {
    id: string;
    ownerId: string;
    readableId: string;
    name: string;
    mediaType: string;
    extension: string | null;
    sizeBytes: number;
    storageKey: string;
    contentHash: string;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `FindAssetArchiveTarget`. */
export interface IFindAssetArchiveTargetResult {
    id: string;
    archivedAt: string | null;
}

/** Result of query `ListActivePageAssetUsages`. */
export interface IListActivePageAssetUsagesResult {
    id: string;
    readableId: string;
    title: string;
    excerpt: string;
    revisionNumber: number;
    createdAt: string;
    updatedAt: string;
    presentation: "embed" | "attachment";
}

/** Result of query `ListActiveEntityImageAssetUsages`. */
export interface IListActiveEntityImageAssetUsagesResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    isSelf: number;
}

/** Result of query `CreateEntity`. */
export interface ICreateEntityResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    isSelf: number;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `SearchEntities`. */
export interface ISearchEntitiesResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    isSelf: number;
    createdAt: string;
    updatedAt: string;
    imageId: string | null;
    imageReadableId: string | null;
    imageName: string | null;
    imageMediaType: string | null;
    imageExtension: string | null;
    imageSizeBytes: number | null;
    imageCreatedAt: string | null;
    imageUpdatedAt: string | null;
}

/** Result of query `ListEntities`. */
export interface IListEntitiesResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    isSelf: number;
    createdAt: string;
    updatedAt: string;
    imageId: string | null;
    imageReadableId: string | null;
    imageName: string | null;
    imageMediaType: string | null;
    imageExtension: string | null;
    imageSizeBytes: number | null;
    imageCreatedAt: string | null;
    imageUpdatedAt: string | null;
}

/** Result of query `CountSearchedEntities`. */
export interface ICountSearchedEntitiesResult {
    total: number;
}

/** Result of query `CountEntities`. */
export interface ICountEntitiesResult {
    total: number;
}

/** Result of query `FindEntity`. */
export interface IFindEntityResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    isSelf: number;
    createdAt: string;
    updatedAt: string;
    imageId: string | null;
    imageReadableId: string | null;
    imageName: string | null;
    imageMediaType: string | null;
    imageExtension: string | null;
    imageSizeBytes: number | null;
    imageCreatedAt: string | null;
    imageUpdatedAt: string | null;
}

/** Result of query `UpdateEntityIdentity`. */
export interface IUpdateEntityIdentityResult {
    id: string;
}

/** Result of query `SetEntityImage`. */
export interface ISetEntityImageResult {
    entityId: string;
}

/** Result of query `FindEntityImageRemovalTarget`. */
export interface IFindEntityImageRemovalTargetResult {
    id: string;
}

/** Result of query `FindEntityArchiveTarget`. */
export interface IFindEntityArchiveTargetResult {
    id: string;
    archivedAt: string | null;
    isSelf: number;
}

/** Result of query `ListActiveEntityMentioningPages`. */
export interface IListActiveEntityMentioningPagesResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `PingDatabase`. */
export interface IPingDatabaseResult {
    value: number;
}

/** Result of query `FindCurrentKnowledgePage`. */
export interface IFindCurrentKnowledgePageResult {
    id: string;
    ownerId: string;
    readableId: string;
    currentRevisionId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    storageKey: string;
    contentHash: string;
    sizeBytes: number;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `ResolveEntityLink`. */
export interface IResolveEntityLinkResult {
    id: string;
}

/** Result of query `ResolvePageLink`. */
export interface IResolvePageLinkResult {
    id: string;
}

/** Result of query `ResolveAssetLink`. */
export interface IResolveAssetLinkResult {
    id: string;
}

/** Result of query `CreateKnowledgePage`. */
export interface ICreateKnowledgePageResult {
    id: string;
}

/** Result of query `SearchKnowledgePages`. */
export interface ISearchKnowledgePagesResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `ListKnowledgePages`. */
export interface IListKnowledgePagesResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `CountSearchedKnowledgePages`. */
export interface ICountSearchedKnowledgePagesResult {
    total: number;
}

/** Result of query `CountKnowledgePages`. */
export interface ICountKnowledgePagesResult {
    total: number;
}

/** Result of query `ListKnowledgePagesByEntity`. */
export interface IListKnowledgePagesByEntityResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `FindKnowledgePage`. */
export interface IFindKnowledgePageResult {
    id: string;
    ownerId: string;
    readableId: string;
    currentRevisionId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    storageKey: string;
    contentHash: string;
    sizeBytes: number;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `FindKnowledgePageArchiveTarget`. */
export interface IFindKnowledgePageArchiveTargetResult {
    id: string;
    currentRevisionId: string;
    archivedAt: string | null;
}

/** Result of query `ListKnowledgePageMentions`. */
export interface IListKnowledgePageMentionsResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    isSelf: number;
    createdAt: string;
    updatedAt: string;
    imageId: string | null;
    imageReadableId: string | null;
    imageName: string | null;
    imageMediaType: string | null;
    imageExtension: string | null;
    imageSizeBytes: number | null;
    imageCreatedAt: string | null;
    imageUpdatedAt: string | null;
}

/** Result of query `ListKnowledgePageRevisions`. */
export interface IListKnowledgePageRevisionsResult {
    revisionNumber: number;
    title: string;
    createdAt: string;
}

/** Result of query `ListCurrentKnowledgePages`. */
export interface IListCurrentKnowledgePagesResult {
    id: string;
    ownerId: string;
    readableId: string;
    currentRevisionId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    storageKey: string;
    contentHash: string;
    sizeBytes: number;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `FindKnowledgePageForIndexReplacement`. */
export interface IFindKnowledgePageForIndexReplacementResult {
    id: string;
    currentRevisionId: string;
}

/** Result of query `ListActiveKnowledgePageReferrers`. */
export interface IListActiveKnowledgePageReferrersResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    createdAt: string;
    updatedAt: string;
    fragment: string;
}

/** Result of query `ListKnowledgePageReferences`. */
export interface IListKnowledgePageReferencesResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    createdAt: string;
    updatedAt: string;
    fragment: string;
}

/** Result of query `ListKnowledgePageBacklinks`. */
export interface IListKnowledgePageBacklinksResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    createdAt: string;
    updatedAt: string;
    fragment: string;
}

/** Result of query `ListKnowledgePageAssetUsages`. */
export interface IListKnowledgePageAssetUsagesResult {
    id: string;
    readableId: string;
    name: string;
    mediaType: string;
    extension: string | null;
    sizeBytes: number;
    createdAt: string;
    updatedAt: string;
    presentation: "embed" | "attachment";
}

/** Result of query `FindKnowledgeProfileOwner`. */
export interface IFindKnowledgeProfileOwnerResult {
    ownerId: string;
}

/** Result of query `CreateKnowledgeProfileEntity`. */
export interface ICreateKnowledgeProfileEntityResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `FindKnowledgeProfile`. */
export interface IFindKnowledgeProfileResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    isSelf: number;
    createdAt: string;
    updatedAt: string;
    imageId: string | null;
    imageReadableId: string | null;
    imageName: string | null;
    imageMediaType: string | null;
    imageExtension: string | null;
    imageSizeBytes: number | null;
    imageCreatedAt: string | null;
    imageUpdatedAt: string | null;
}

/** Result of query `ReadOwnerRegistrationState`. */
export interface IReadOwnerRegistrationStateResult {
    ownerExists: number;
    passkeyExists: number;
}

export interface Queries {
    CreateAsset: ICreateAssetResult;
    SearchAssets: ISearchAssetsResult;
    ListAssets: IListAssetsResult;
    CountSearchedAssets: ICountSearchedAssetsResult;
    CountAssets: ICountAssetsResult;
    FindAsset: IFindAssetResult;
    UpdateAssetName: IUpdateAssetNameResult;
    FindAssetArchiveTarget: IFindAssetArchiveTargetResult;
    ListActivePageAssetUsages: IListActivePageAssetUsagesResult;
    ListActiveEntityImageAssetUsages: IListActiveEntityImageAssetUsagesResult;
    CreateEntity: ICreateEntityResult;
    SearchEntities: ISearchEntitiesResult;
    ListEntities: IListEntitiesResult;
    CountSearchedEntities: ICountSearchedEntitiesResult;
    CountEntities: ICountEntitiesResult;
    FindEntity: IFindEntityResult;
    UpdateEntityIdentity: IUpdateEntityIdentityResult;
    SetEntityImage: ISetEntityImageResult;
    FindEntityImageRemovalTarget: IFindEntityImageRemovalTargetResult;
    FindEntityArchiveTarget: IFindEntityArchiveTargetResult;
    ListActiveEntityMentioningPages: IListActiveEntityMentioningPagesResult;
    PingDatabase: IPingDatabaseResult;
    FindCurrentKnowledgePage: IFindCurrentKnowledgePageResult;
    ResolveEntityLink: IResolveEntityLinkResult;
    ResolvePageLink: IResolvePageLinkResult;
    ResolveAssetLink: IResolveAssetLinkResult;
    CreateKnowledgePage: ICreateKnowledgePageResult;
    SearchKnowledgePages: ISearchKnowledgePagesResult;
    ListKnowledgePages: IListKnowledgePagesResult;
    CountSearchedKnowledgePages: ICountSearchedKnowledgePagesResult;
    CountKnowledgePages: ICountKnowledgePagesResult;
    ListKnowledgePagesByEntity: IListKnowledgePagesByEntityResult;
    FindKnowledgePage: IFindKnowledgePageResult;
    FindKnowledgePageArchiveTarget: IFindKnowledgePageArchiveTargetResult;
    ListKnowledgePageMentions: IListKnowledgePageMentionsResult;
    ListKnowledgePageRevisions: IListKnowledgePageRevisionsResult;
    ListCurrentKnowledgePages: IListCurrentKnowledgePagesResult;
    FindKnowledgePageForIndexReplacement: IFindKnowledgePageForIndexReplacementResult;
    ListActiveKnowledgePageReferrers: IListActiveKnowledgePageReferrersResult;
    ListKnowledgePageReferences: IListKnowledgePageReferencesResult;
    ListKnowledgePageBacklinks: IListKnowledgePageBacklinksResult;
    ListKnowledgePageAssetUsages: IListKnowledgePageAssetUsagesResult;
    FindKnowledgeProfileOwner: IFindKnowledgeProfileOwnerResult;
    CreateKnowledgeProfileEntity: ICreateKnowledgeProfileEntityResult;
    FindKnowledgeProfile: IFindKnowledgeProfileResult;
    ReadOwnerRegistrationState: IReadOwnerRegistrationStateResult;
}

declare module "@ilbertt/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
}

export {};
