// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `CreateAsset`. */
export interface ICreateAssetResult {
    id: string;
    ownerId: string;
    readableId: string;
    name: string;
    mediaType: string;
    extension: string | null;
    sizeBytes: number;
    storageKey: string;
    contentHash: string;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `ListAssets`. */
export interface IListAssetsResult {
    id: string;
    readableId: string;
    name: string;
    mediaType: string;
    extension: string | null;
    sizeBytes: number;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `CountAssets`. */
export interface ICountAssetsResult {
    total: number;
}

/** Result of query `FindAsset`. */
export interface IFindAssetResult {
    id: string;
    ownerId: string;
    readableId: string;
    name: string;
    mediaType: string;
    extension: string | null;
    sizeBytes: number;
    storageKey: string;
    contentHash: string;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `UpdateAssetName`. */
export interface IUpdateAssetNameResult {
    id: string;
    ownerId: string;
    readableId: string;
    name: string;
    mediaType: string;
    extension: string | null;
    sizeBytes: number;
    storageKey: string;
    contentHash: string;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `FindAssetArchiveTarget`. */
export interface IFindAssetArchiveTargetResult {
    id: string;
    archivedAt: string | null;
}

/** Result of query `RemoveAssetSearchDocument`. */
export interface IRemoveAssetSearchDocumentResult {
}

/** Result of query `ListAssetDepictedPeople`. */
export interface IListAssetDepictedPeopleResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    entityType: string | null;
    isSelf: number;
    source: "detected" | "confirmed";
}

/** Result of query `ListActivePageAssetUsages`. */
export interface IListActivePageAssetUsagesResult {
    id: string;
    readableId: string;
    title: string;
    excerpt: string;
    revisionNumber: number;
    temporalCoverage: string | null;
    createdAt: string;
    updatedAt: string;
    presentation: "embed" | "attachment";
}

/** Result of query `ListActiveEntityImageAssetUsages`. */
export interface IListActiveEntityImageAssetUsagesResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    entityType: string | null;
    isSelf: number;
}

/** Result of query `CreateEntity`. */
export interface ICreateEntityResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    entityType: string | null;
    isSelf: number;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `ListEntities`. */
export interface IListEntitiesResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    entityType: string | null;
    isSelf: number;
    createdAt: string;
    updatedAt: string;
    imageId: string | null;
    imageReadableId: string | null;
    imageName: string | null;
    imageMediaType: string | null;
    imageExtension: string | null;
    imageSizeBytes: number | null;
    imageCreatedAt: string | null;
    imageUpdatedAt: string | null;
}

/** Result of query `CountEntities`. */
export interface ICountEntitiesResult {
    total: number;
}

/** Result of query `FindEntity`. */
export interface IFindEntityResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    entityType: string | null;
    isSelf: number;
    createdAt: string;
    updatedAt: string;
    imageId: string | null;
    imageReadableId: string | null;
    imageName: string | null;
    imageMediaType: string | null;
    imageExtension: string | null;
    imageSizeBytes: number | null;
    imageCreatedAt: string | null;
    imageUpdatedAt: string | null;
}

/** Result of query `UpdateEntityIdentity`. */
export interface IUpdateEntityIdentityResult {
    id: string;
}

/** Result of query `SetEntityImage`. */
export interface ISetEntityImageResult {
    entityId: string;
}

/** Result of query `FindEntityImageAssignment`. */
export interface IFindEntityImageAssignmentResult {
    entityId: string;
}

/** Result of query `RemoveEntityImage`. */
export interface IRemoveEntityImageResult {
    id: string;
}

/** Result of query `FindEntityArchiveTarget`. */
export interface IFindEntityArchiveTargetResult {
    id: string;
    archivedAt: string | null;
    isSelf: number;
}

/** Result of query `RemoveEntitySearchDocument`. */
export interface IRemoveEntitySearchDocumentResult {
}

/** Result of query `ListActiveEntityMentioningPages`. */
export interface IListActiveEntityMentioningPagesResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    temporalCoverage: string | null;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `ReadFaceObservations`. */
export interface IReadFaceObservationsResult {
    id: string;
    readableId: string;
    assetId: string;
    box: string;
    cropKey: string;
    detectionScore: number;
    analysisVersion: string;
    current: number;
    needsReview: number;
    embeddingSpace: string;
    embeddingRevision: string;
    vector: Uint8Array;
    protected: unknown;
}

/** Result of query `ReadFaceAnalysis`. */
export interface IReadFaceAnalysisResult {
    state: "processing" | "ready" | "failed";
    error: string | null;
    analysisVersion: string;
}

/** Result of query `ReadAssetFaceViews`. */
export interface IReadAssetFaceViewsResult {
    readableId: string;
    box: string;
    current: number;
    needsReview: number;
    decision: string | null;
    entityId: string | null;
    entityReadableId: string | null;
    name: string | null;
    description: string | null;
    entityType: string | null;
    selfEntityId: string | null;
    similarity: number | null;
}

/** Result of query `CheckFaceAnalysisAttempt`. */
export interface ICheckFaceAnalysisAttemptResult {
    assetId: string;
}

/** Result of query `ListFaceReferences`. */
export interface IListFaceReferencesResult {
    entityId: string;
    faceId: string;
    assetId: string;
    embeddingSpace: string;
    embeddingRevision: string;
    vector: Uint8Array;
}

/** Result of query `SelectPersonReferenceFace`. */
export interface ISelectPersonReferenceFaceResult {
    faceId: string;
}

/** Result of query `ReadPersonReferenceFace`. */
export interface IReadPersonReferenceFaceResult {
    readableId: string;
}

/** Result of query `FindFaceAnnotationTarget`. */
export interface IFindFaceAnnotationTargetResult {
    id: string;
}

/** Result of query `ReadFaceThreshold`. */
export interface IReadFaceThresholdResult {
    threshold: number;
}

/** Result of query `FaceAssetBatch`. */
export interface IFaceAssetBatchResult {
    id: string;
    readableId: string;
    mediaType: string;
}

/** Result of query `ListPersonImages`. */
export interface IListPersonImagesResult {
    id: string;
    readableId: string;
    name: string;
    mediaType: string;
    extension: string | null;
    sizeBytes: number;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `PingDatabase`. */
export interface IPingDatabaseResult {
    value: number;
}

/** Result of query `SearchHypermedia`. */
export interface ISearchHypermediaResult {
    total: number;
    resourceType: "entity" | "knowledge_page" | "asset" | "record";
    readableId: string;
    participantNames: string;
    storageKey: string;
    contentHash: string;
    contentSizeBytes: number;
    entityId: string | null;
    entityName: string | null;
    entityDescription: string | null;
    entityType: string | null;
    isSelf: number;
    imageId: string | null;
    imageReadableId: string | null;
    imageName: string | null;
    imageMediaType: string | null;
    imageExtension: string | null;
    imageSizeBytes: number | null;
    imageCreatedAt: string | null;
    imageUpdatedAt: string | null;
    pageId: string | null;
    pageTitle: string | null;
    pageExcerpt: string | null;
    revisionNumber: number;
    temporalCoverage: string | null;
    assetId: string | null;
    assetName: string | null;
    mediaType: string | null;
    assetExtension: string | null;
    assetSizeBytes: number | null;
    recordTitle: string | null;
    recordProvider: string | null;
    sourceCreatedAt: string | null;
    sourceUpdatedAt: string | null;
    recordKind: string | null;
    recordId: string | null;
    syncReadableId: string | null;
    syncName: string | null;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `FindHypermediaEntity`. */
export interface IFindHypermediaEntityResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    entityType: string | null;
    isSelf: number;
    imageId: string | null;
    imageReadableId: string | null;
    imageName: string | null;
    imageMediaType: string | null;
    imageExtension: string | null;
    imageSizeBytes: number | null;
    imageCreatedAt: string | null;
    imageUpdatedAt: string | null;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `ListHypermediaEntityNeighbors`. */
export interface IListHypermediaEntityNeighborsResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    entityType: string | null;
    isSelf: number;
    imageId: string | null;
    imageReadableId: string | null;
    imageName: string | null;
    imageMediaType: string | null;
    imageExtension: string | null;
    imageSizeBytes: number | null;
    imageCreatedAt: string | null;
    imageUpdatedAt: string | null;
    createdAt: string;
    updatedAt: string;
    sharedPageCount: number;
}

/** Result of query `ListHypermediaPages`. */
export interface IListHypermediaPagesResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    temporalCoverage: string | null;
    ongoingSort: number;
    latestSort: unknown | null;
    startSort: unknown | null;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `ListHypermediaPageEntities`. */
export interface IListHypermediaPageEntitiesResult {
    sourcePageReadableId: string;
    readableId: string;
}

/** Result of query `FindKnowledgePageOwnerRevisionAuthor`. */
export interface IFindKnowledgePageOwnerRevisionAuthorResult {
    name: string;
}

/** Result of query `FindCurrentKnowledgePage`. */
export interface IFindCurrentKnowledgePageResult {
    id: string;
    ownerId: string;
    readableId: string;
    currentRevisionId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    temporalCoverage: string | null;
    storageKey: string;
    contentHash: string;
    sizeBytes: number;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `ResolveRecordLink`. */
export interface IResolveRecordLinkResult {
    readable_id: string | null;
}

/** Result of query `ResolveEntityLink`. */
export interface IResolveEntityLinkResult {
    id: string;
}

/** Result of query `ResolvePageLink`. */
export interface IResolvePageLinkResult {
    id: string;
}

/** Result of query `ResolveAssetLink`. */
export interface IResolveAssetLinkResult {
    id: string;
}

/** Result of query `CreateKnowledgePage`. */
export interface ICreateKnowledgePageResult {
    id: string;
}

/** Result of query `ListKnowledgePages`. */
export interface IListKnowledgePagesResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    temporalCoverage: string | null;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `CountKnowledgePages`. */
export interface ICountKnowledgePagesResult {
    total: number;
}

/** Result of query `ListKnowledgePagesByEntity`. */
export interface IListKnowledgePagesByEntityResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    temporalCoverage: string | null;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `FindKnowledgePage`. */
export interface IFindKnowledgePageResult {
    id: string;
    ownerId: string;
    readableId: string;
    currentRevisionId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    temporalCoverage: string | null;
    storageKey: string;
    contentHash: string;
    sizeBytes: number;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `FindKnowledgePageArchiveTarget`. */
export interface IFindKnowledgePageArchiveTargetResult {
    id: string;
    currentRevisionId: string;
    archivedAt: string | null;
}

/** Result of query `RemoveKnowledgePageSearchDocument`. */
export interface IRemoveKnowledgePageSearchDocumentResult {
}

/** Result of query `ListKnowledgePageMentions`. */
export interface IListKnowledgePageMentionsResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    entityType: string | null;
    isSelf: number;
    createdAt: string;
    updatedAt: string;
    imageId: string | null;
    imageReadableId: string | null;
    imageName: string | null;
    imageMediaType: string | null;
    imageExtension: string | null;
    imageSizeBytes: number | null;
    imageCreatedAt: string | null;
    imageUpdatedAt: string | null;
}

/** Result of query `ListKnowledgePageRevisions`. */
export interface IListKnowledgePageRevisionsResult {
    revisionNumber: number;
    title: string;
    temporalCoverage: string | null;
    authorKind: string;
    authorName: string | null;
    createdAt: string;
}

/** Result of query `ListActiveKnowledgePageReferrers`. */
export interface IListActiveKnowledgePageReferrersResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    temporalCoverage: string | null;
    createdAt: string;
    updatedAt: string;
    fragment: string;
}

/** Result of query `ListKnowledgePageRecordReferences`. */
export interface IListKnowledgePageRecordReferencesResult {
    readableId: string;
    title: string | null;
    provider: string;
    kind: string;
    available: unknown;
}

/** Result of query `ListKnowledgePageReferences`. */
export interface IListKnowledgePageReferencesResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    temporalCoverage: string | null;
    createdAt: string;
    updatedAt: string;
    fragment: string;
}

/** Result of query `ListKnowledgePageBacklinks`. */
export interface IListKnowledgePageBacklinksResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    temporalCoverage: string | null;
    createdAt: string;
    updatedAt: string;
    fragment: string;
}

/** Result of query `ListKnowledgePageAssetUsages`. */
export interface IListKnowledgePageAssetUsagesResult {
    id: string;
    readableId: string;
    name: string;
    mediaType: string;
    extension: string | null;
    sizeBytes: number;
    createdAt: string;
    updatedAt: string;
    presentation: "embed" | "attachment";
}

/** Result of query `FindKnowledgeProfileOwner`. */
export interface IFindKnowledgeProfileOwnerResult {
    ownerId: string;
}

/** Result of query `CreateKnowledgeProfileEntity`. */
export interface ICreateKnowledgeProfileEntityResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    entityType: string | null;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `FindKnowledgeProfile`. */
export interface IFindKnowledgeProfileResult {
    id: string;
    readableId: string;
    name: string;
    description: string;
    entityType: string | null;
    isSelf: number;
    createdAt: string;
    updatedAt: string;
    imageId: string | null;
    imageReadableId: string | null;
    imageName: string | null;
    imageMediaType: string | null;
    imageExtension: string | null;
    imageSizeBytes: number | null;
    imageCreatedAt: string | null;
    imageUpdatedAt: string | null;
}

/** Result of query `FindMcpOAuthClient`. */
export interface IFindMcpOAuthClientResult {
    clientId: string;
    clientDiscoveryId: string | null;
    name: string | null;
}

/** Result of query `FindActiveMcpClientAuthorization`. */
export interface IFindActiveMcpClientAuthorizationResult {
    id: string;
    ownerId: string;
    name: string;
    oauthClientId: string;
    verifiedClientId: string | null;
    createdAt: string;
    updatedAt: string;
    archivedAt: string | null;
}

/** Result of query `FindActiveMcpClientAuthorizationById`. */
export interface IFindActiveMcpClientAuthorizationByIdResult {
    id: string;
    ownerId: string;
    name: string;
    oauthClientId: string;
    verifiedClientId: string | null;
    createdAt: string;
    updatedAt: string;
    archivedAt: string | null;
}

/** Result of query `ListMcpClientAuthorizations`. */
export interface IListMcpClientAuthorizationsResult {
    id: string;
    ownerId: string;
    name: string;
    oauthClientId: string;
    verifiedClientId: string | null;
    createdAt: string;
    updatedAt: string;
    archivedAt: string | null;
}

/** Result of query `RenameActiveMcpClientAuthorization`. */
export interface IRenameActiveMcpClientAuthorizationResult {
    id: string;
    ownerId: string;
    name: string;
    oauthClientId: string;
    verifiedClientId: string | null;
    createdAt: string;
    updatedAt: string;
    archivedAt: string | null;
}

/** Result of query `ReadOwnerRegistrationState`. */
export interface IReadOwnerRegistrationStateResult {
    ownerExists: number;
    passkeyExists: number;
}

/** Result of query `FindCurrentRecordRevision`. */
export interface IFindCurrentRecordRevisionResult {
    revision: number;
    revisionHash: string;
    readableId: string;
    storageKey: string;
}

/** Result of query `ApplyRecordRevision`. */
export interface IApplyRecordRevisionResult {
}

/** Result of query `RemoveRecordSearchDocument`. */
export interface IRemoveRecordSearchDocumentResult {
}

/** Result of query `FindActiveRecordSyncForAcceptance`. */
export interface IFindActiveRecordSyncForAcceptanceResult {
    id: string;
    ownerId: string;
}

/** Result of query `ListRecordResources`. */
export interface IListRecordResourcesResult {
    readableId: string;
    title: string;
    provider: string;
    kind: string;
    recordId: string;
    sourceCreatedAt: string | null;
    sourceUpdatedAt: string | null;
    syncReadableId: string;
    syncName: string;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `RecordFilterOptions`. */
export interface IRecordFilterOptionsResult {
    provider: string;
    kind: string;
}

/** Result of query `FindRecordResource`. */
export interface IFindRecordResourceResult {
    title: string;
    provider: string;
    sourceCreatedAt: string | null;
    sourceUpdatedAt: string | null;
    syncReadableId: string;
    syncName: string;
    readableId: string;
    kind: string;
    recordId: string;
    storageKey: string;
    contentHash: string;
    sizeBytes: number;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `ListRecordBacklinks`. */
export interface IListRecordBacklinksResult {
    id: string;
    readableId: string;
    revisionNumber: number;
    title: string;
    excerpt: string;
    temporalCoverage: string | null;
    createdAt: string;
    updatedAt: string;
}

/** Result of query `FindActiveRecordSyncByName`. */
export interface IFindActiveRecordSyncByNameResult {
    id: string;
}

/** Result of query `CreateRecordSync`. */
export interface ICreateRecordSyncResult {
    id: string | null;
}

/** Result of query `ListRecordSyncs`. */
export interface IListRecordSyncsResult {
    readableId: string;
    name: string;
    createdAt: string;
    revokedAt: string | null;
}

/** Result of query `RevokeRecordSync`. */
export interface IRevokeRecordSyncResult {
    id: string | null;
}

/** Result of query `AuthenticateRecordSyncApiKey`. */
export interface IAuthenticateRecordSyncApiKeyResult {
    syncId: string;
    ownerId: string;
}

export interface Queries {
    CreateAsset: ICreateAssetResult;
    ListAssets: IListAssetsResult;
    CountAssets: ICountAssetsResult;
    FindAsset: IFindAssetResult;
    UpdateAssetName: IUpdateAssetNameResult;
    FindAssetArchiveTarget: IFindAssetArchiveTargetResult;
    RemoveAssetSearchDocument: IRemoveAssetSearchDocumentResult;
    ListAssetDepictedPeople: IListAssetDepictedPeopleResult;
    ListActivePageAssetUsages: IListActivePageAssetUsagesResult;
    ListActiveEntityImageAssetUsages: IListActiveEntityImageAssetUsagesResult;
    CreateEntity: ICreateEntityResult;
    ListEntities: IListEntitiesResult;
    CountEntities: ICountEntitiesResult;
    FindEntity: IFindEntityResult;
    UpdateEntityIdentity: IUpdateEntityIdentityResult;
    SetEntityImage: ISetEntityImageResult;
    FindEntityImageAssignment: IFindEntityImageAssignmentResult;
    RemoveEntityImage: IRemoveEntityImageResult;
    FindEntityArchiveTarget: IFindEntityArchiveTargetResult;
    RemoveEntitySearchDocument: IRemoveEntitySearchDocumentResult;
    ListActiveEntityMentioningPages: IListActiveEntityMentioningPagesResult;
    ReadFaceObservations: IReadFaceObservationsResult;
    ReadFaceAnalysis: IReadFaceAnalysisResult;
    ReadAssetFaceViews: IReadAssetFaceViewsResult;
    CheckFaceAnalysisAttempt: ICheckFaceAnalysisAttemptResult;
    ListFaceReferences: IListFaceReferencesResult;
    SelectPersonReferenceFace: ISelectPersonReferenceFaceResult;
    ReadPersonReferenceFace: IReadPersonReferenceFaceResult;
    FindFaceAnnotationTarget: IFindFaceAnnotationTargetResult;
    ReadFaceThreshold: IReadFaceThresholdResult;
    FaceAssetBatch: IFaceAssetBatchResult;
    ListPersonImages: IListPersonImagesResult;
    PingDatabase: IPingDatabaseResult;
    SearchHypermedia: ISearchHypermediaResult;
    FindHypermediaEntity: IFindHypermediaEntityResult;
    ListHypermediaEntityNeighbors: IListHypermediaEntityNeighborsResult;
    ListHypermediaPages: IListHypermediaPagesResult;
    ListHypermediaPageEntities: IListHypermediaPageEntitiesResult;
    FindKnowledgePageOwnerRevisionAuthor: IFindKnowledgePageOwnerRevisionAuthorResult;
    FindCurrentKnowledgePage: IFindCurrentKnowledgePageResult;
    ResolveRecordLink: IResolveRecordLinkResult;
    ResolveEntityLink: IResolveEntityLinkResult;
    ResolvePageLink: IResolvePageLinkResult;
    ResolveAssetLink: IResolveAssetLinkResult;
    CreateKnowledgePage: ICreateKnowledgePageResult;
    ListKnowledgePages: IListKnowledgePagesResult;
    CountKnowledgePages: ICountKnowledgePagesResult;
    ListKnowledgePagesByEntity: IListKnowledgePagesByEntityResult;
    FindKnowledgePage: IFindKnowledgePageResult;
    FindKnowledgePageArchiveTarget: IFindKnowledgePageArchiveTargetResult;
    RemoveKnowledgePageSearchDocument: IRemoveKnowledgePageSearchDocumentResult;
    ListKnowledgePageMentions: IListKnowledgePageMentionsResult;
    ListKnowledgePageRevisions: IListKnowledgePageRevisionsResult;
    ListActiveKnowledgePageReferrers: IListActiveKnowledgePageReferrersResult;
    ListKnowledgePageRecordReferences: IListKnowledgePageRecordReferencesResult;
    ListKnowledgePageReferences: IListKnowledgePageReferencesResult;
    ListKnowledgePageBacklinks: IListKnowledgePageBacklinksResult;
    ListKnowledgePageAssetUsages: IListKnowledgePageAssetUsagesResult;
    FindKnowledgeProfileOwner: IFindKnowledgeProfileOwnerResult;
    CreateKnowledgeProfileEntity: ICreateKnowledgeProfileEntityResult;
    FindKnowledgeProfile: IFindKnowledgeProfileResult;
    FindMcpOAuthClient: IFindMcpOAuthClientResult;
    FindActiveMcpClientAuthorization: IFindActiveMcpClientAuthorizationResult;
    FindActiveMcpClientAuthorizationById: IFindActiveMcpClientAuthorizationByIdResult;
    ListMcpClientAuthorizations: IListMcpClientAuthorizationsResult;
    RenameActiveMcpClientAuthorization: IRenameActiveMcpClientAuthorizationResult;
    ReadOwnerRegistrationState: IReadOwnerRegistrationStateResult;
    FindCurrentRecordRevision: IFindCurrentRecordRevisionResult;
    ApplyRecordRevision: IApplyRecordRevisionResult;
    RemoveRecordSearchDocument: IRemoveRecordSearchDocumentResult;
    FindActiveRecordSyncForAcceptance: IFindActiveRecordSyncForAcceptanceResult;
    ListRecordResources: IListRecordResourcesResult;
    RecordFilterOptions: IRecordFilterOptionsResult;
    FindRecordResource: IFindRecordResourceResult;
    ListRecordBacklinks: IListRecordBacklinksResult;
    FindActiveRecordSyncByName: IFindActiveRecordSyncByNameResult;
    CreateRecordSync: ICreateRecordSyncResult;
    ListRecordSyncs: IListRecordSyncsResult;
    RevokeRecordSync: IRevokeRecordSyncResult;
    AuthenticateRecordSyncApiKey: IAuthenticateRecordSyncApiKeyResult;
}

declare module "@ilbertt/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
}

export {};
