/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PagesRouteImport } from './routes/pages'
import { Route as EntitiesIndexRouteImport } from './routes/entities.index'
import { Route as EntitiesIdRouteImport } from './routes/entities.$id'
import { Route as PagesIndexRouteImport } from './routes/pages.index'
import { Route as PagesIdRouteImport } from './routes/pages.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesIndexRoute = EntitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntitiesRoute,
} as any)
const EntitiesIdRoute = EntitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EntitiesRoute,
} as any)
const PagesIndexRoute = PagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesRoute,
} as any)
const PagesIdRoute = PagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entities': typeof EntitiesRouteWithChildren
  '/login': typeof LoginRoute
  '/pages': typeof PagesRouteWithChildren
  '/entities/$id': typeof EntitiesIdRoute
  '/pages/$id': typeof PagesIdRoute
  '/entities/': typeof EntitiesIndexRoute
  '/pages/': typeof PagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/entities/$id': typeof EntitiesIdRoute
  '/pages/$id': typeof PagesIdRoute
  '/entities': typeof EntitiesIndexRoute
  '/pages': typeof PagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entities': typeof EntitiesRouteWithChildren
  '/login': typeof LoginRoute
  '/pages': typeof PagesRouteWithChildren
  '/entities/$id': typeof EntitiesIdRoute
  '/pages/$id': typeof PagesIdRoute
  '/entities/': typeof EntitiesIndexRoute
  '/pages/': typeof PagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entities'
    | '/login'
    | '/pages'
    | '/entities/$id'
    | '/pages/$id'
    | '/entities/'
    | '/pages/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/entities/$id' | '/pages/$id' | '/entities' | '/pages'
  id:
    | '__root__'
    | '/'
    | '/entities'
    | '/login'
    | '/pages'
    | '/entities/$id'
    | '/pages/$id'
    | '/entities/'
    | '/pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntitiesRoute: typeof EntitiesRouteWithChildren
  LoginRoute: typeof LoginRoute
  PagesRoute: typeof PagesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities/': {
      id: '/entities/'
      path: '/'
      fullPath: '/entities/'
      preLoaderRoute: typeof EntitiesIndexRouteImport
      parentRoute: typeof EntitiesRoute
    }
    '/entities/$id': {
      id: '/entities/$id'
      path: '/$id'
      fullPath: '/entities/$id'
      preLoaderRoute: typeof EntitiesIdRouteImport
      parentRoute: typeof EntitiesRoute
    }
    '/pages/': {
      id: '/pages/'
      path: '/'
      fullPath: '/pages/'
      preLoaderRoute: typeof PagesIndexRouteImport
      parentRoute: typeof PagesRoute
    }
    '/pages/$id': {
      id: '/pages/$id'
      path: '/$id'
      fullPath: '/pages/$id'
      preLoaderRoute: typeof PagesIdRouteImport
      parentRoute: typeof PagesRoute
    }
  }
}

interface EntitiesRouteChildren {
  EntitiesIdRoute: typeof EntitiesIdRoute
  EntitiesIndexRoute: typeof EntitiesIndexRoute
}

const EntitiesRouteChildren: EntitiesRouteChildren = {
  EntitiesIdRoute: EntitiesIdRoute,
  EntitiesIndexRoute: EntitiesIndexRoute,
}

const EntitiesRouteWithChildren = EntitiesRoute._addFileChildren(
  EntitiesRouteChildren,
)

interface PagesRouteChildren {
  PagesIdRoute: typeof PagesIdRoute
  PagesIndexRoute: typeof PagesIndexRoute
}

const PagesRouteChildren: PagesRouteChildren = {
  PagesIdRoute: PagesIdRoute,
  PagesIndexRoute: PagesIndexRoute,
}

const PagesRouteWithChildren = PagesRoute._addFileChildren(PagesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntitiesRoute: EntitiesRouteWithChildren,
  LoginRoute: LoginRoute,
  PagesRoute: PagesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
