/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as PagesRouteImport } from './routes/pages'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AssetsIndexRouteImport } from './routes/assets.index'
import { Route as AssetsIdRouteImport } from './routes/assets.$id'
import { Route as AssetsNewRouteImport } from './routes/assets.new'
import { Route as EntitiesIndexRouteImport } from './routes/entities.index'
import { Route as EntitiesIdRouteImport } from './routes/entities.$id'
import { Route as EntitiesNewRouteImport } from './routes/entities.new'
import { Route as McpAuthorizeRouteImport } from './routes/mcp.authorize'
import { Route as PagesIndexRouteImport } from './routes/pages.index'
import { Route as PagesIdRouteImport } from './routes/pages.$id'
import { Route as PagesNewRouteImport } from './routes/pages.new'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsIdRoute = AssetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsNewRoute = AssetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AssetsRoute,
} as any)
const EntitiesIndexRoute = EntitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EntitiesRoute,
} as any)
const EntitiesIdRoute = EntitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EntitiesRoute,
} as any)
const EntitiesNewRoute = EntitiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EntitiesRoute,
} as any)
const McpAuthorizeRoute = McpAuthorizeRouteImport.update({
  id: '/mcp/authorize',
  path: '/mcp/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesIndexRoute = PagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesRoute,
} as any)
const PagesIdRoute = PagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PagesRoute,
} as any)
const PagesNewRoute = PagesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PagesRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/entities': typeof EntitiesRouteWithChildren
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/pages': typeof PagesRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/assets/$id': typeof AssetsIdRoute
  '/assets/new': typeof AssetsNewRoute
  '/entities/$id': typeof EntitiesIdRoute
  '/entities/new': typeof EntitiesNewRoute
  '/mcp/authorize': typeof McpAuthorizeRoute
  '/pages/$id': typeof PagesIdRoute
  '/pages/new': typeof PagesNewRoute
  '/assets/': typeof AssetsIndexRoute
  '/entities/': typeof EntitiesIndexRoute
  '/pages/': typeof PagesIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/setup': typeof SetupRoute
  '/assets/$id': typeof AssetsIdRoute
  '/assets/new': typeof AssetsNewRoute
  '/entities/$id': typeof EntitiesIdRoute
  '/entities/new': typeof EntitiesNewRoute
  '/mcp/authorize': typeof McpAuthorizeRoute
  '/pages/$id': typeof PagesIdRoute
  '/pages/new': typeof PagesNewRoute
  '/assets': typeof AssetsIndexRoute
  '/entities': typeof EntitiesIndexRoute
  '/pages': typeof PagesIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/entities': typeof EntitiesRouteWithChildren
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/pages': typeof PagesRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/assets/$id': typeof AssetsIdRoute
  '/assets/new': typeof AssetsNewRoute
  '/entities/$id': typeof EntitiesIdRoute
  '/entities/new': typeof EntitiesNewRoute
  '/mcp/authorize': typeof McpAuthorizeRoute
  '/pages/$id': typeof PagesIdRoute
  '/pages/new': typeof PagesNewRoute
  '/assets/': typeof AssetsIndexRoute
  '/entities/': typeof EntitiesIndexRoute
  '/pages/': typeof PagesIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/entities'
    | '/login'
    | '/map'
    | '/pages'
    | '/settings'
    | '/setup'
    | '/assets/$id'
    | '/assets/new'
    | '/entities/$id'
    | '/entities/new'
    | '/mcp/authorize'
    | '/pages/$id'
    | '/pages/new'
    | '/assets/'
    | '/entities/'
    | '/pages/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/map'
    | '/setup'
    | '/assets/$id'
    | '/assets/new'
    | '/entities/$id'
    | '/entities/new'
    | '/mcp/authorize'
    | '/pages/$id'
    | '/pages/new'
    | '/assets'
    | '/entities'
    | '/pages'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/entities'
    | '/login'
    | '/map'
    | '/pages'
    | '/settings'
    | '/setup'
    | '/assets/$id'
    | '/assets/new'
    | '/entities/$id'
    | '/entities/new'
    | '/mcp/authorize'
    | '/pages/$id'
    | '/pages/new'
    | '/assets/'
    | '/entities/'
    | '/pages/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRouteWithChildren
  EntitiesRoute: typeof EntitiesRouteWithChildren
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  PagesRoute: typeof PagesRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  SetupRoute: typeof SetupRoute
  McpAuthorizeRoute: typeof McpAuthorizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/$id': {
      id: '/assets/$id'
      path: '/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AssetsIdRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/new': {
      id: '/assets/new'
      path: '/new'
      fullPath: '/assets/new'
      preLoaderRoute: typeof AssetsNewRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/entities/': {
      id: '/entities/'
      path: '/'
      fullPath: '/entities/'
      preLoaderRoute: typeof EntitiesIndexRouteImport
      parentRoute: typeof EntitiesRoute
    }
    '/entities/$id': {
      id: '/entities/$id'
      path: '/$id'
      fullPath: '/entities/$id'
      preLoaderRoute: typeof EntitiesIdRouteImport
      parentRoute: typeof EntitiesRoute
    }
    '/entities/new': {
      id: '/entities/new'
      path: '/new'
      fullPath: '/entities/new'
      preLoaderRoute: typeof EntitiesNewRouteImport
      parentRoute: typeof EntitiesRoute
    }
    '/mcp/authorize': {
      id: '/mcp/authorize'
      path: '/mcp/authorize'
      fullPath: '/mcp/authorize'
      preLoaderRoute: typeof McpAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/': {
      id: '/pages/'
      path: '/'
      fullPath: '/pages/'
      preLoaderRoute: typeof PagesIndexRouteImport
      parentRoute: typeof PagesRoute
    }
    '/pages/$id': {
      id: '/pages/$id'
      path: '/$id'
      fullPath: '/pages/$id'
      preLoaderRoute: typeof PagesIdRouteImport
      parentRoute: typeof PagesRoute
    }
    '/pages/new': {
      id: '/pages/new'
      path: '/new'
      fullPath: '/pages/new'
      preLoaderRoute: typeof PagesNewRouteImport
      parentRoute: typeof PagesRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface AssetsRouteChildren {
  AssetsIdRoute: typeof AssetsIdRoute
  AssetsNewRoute: typeof AssetsNewRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
}

const AssetsRouteChildren: AssetsRouteChildren = {
  AssetsIdRoute: AssetsIdRoute,
  AssetsNewRoute: AssetsNewRoute,
  AssetsIndexRoute: AssetsIndexRoute,
}

const AssetsRouteWithChildren =
  AssetsRoute._addFileChildren(AssetsRouteChildren)

interface EntitiesRouteChildren {
  EntitiesIdRoute: typeof EntitiesIdRoute
  EntitiesNewRoute: typeof EntitiesNewRoute
  EntitiesIndexRoute: typeof EntitiesIndexRoute
}

const EntitiesRouteChildren: EntitiesRouteChildren = {
  EntitiesIdRoute: EntitiesIdRoute,
  EntitiesNewRoute: EntitiesNewRoute,
  EntitiesIndexRoute: EntitiesIndexRoute,
}

const EntitiesRouteWithChildren = EntitiesRoute._addFileChildren(
  EntitiesRouteChildren,
)

interface PagesRouteChildren {
  PagesIdRoute: typeof PagesIdRoute
  PagesNewRoute: typeof PagesNewRoute
  PagesIndexRoute: typeof PagesIndexRoute
}

const PagesRouteChildren: PagesRouteChildren = {
  PagesIdRoute: PagesIdRoute,
  PagesNewRoute: PagesNewRoute,
  PagesIndexRoute: PagesIndexRoute,
}

const PagesRouteWithChildren = PagesRoute._addFileChildren(PagesRouteChildren)

interface SettingsRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRouteWithChildren,
  EntitiesRoute: EntitiesRouteWithChildren,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  PagesRoute: PagesRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  SetupRoute: SetupRoute,
  McpAuthorizeRoute: McpAuthorizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
