/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen - do not edit by hand.
import type { InferForwardedOptions, InferParams, RuntimeNode } from '@parshjs/core';
import type { command as agentsyncCmd } from './commands/agent-sync.ts';
import type { command as agentsyncInstallCmd } from './commands/agent-sync/install.ts';
import type { command as agentsyncStatusCmd } from './commands/agent-sync/status.ts';
import type { command as agentsyncSyncnowCmd } from './commands/agent-sync/sync-now.ts';
import type { command as agentsyncUninstallCmd } from './commands/agent-sync/uninstall.ts';
import type { command as cloudBackupCmd } from './commands/cloud/backup.ts';
import type { command as cloudCmd } from './commands/cloud.ts';
import type { command as cloudDestroyCmd } from './commands/cloud/destroy.ts';
import type { command as cloudDoctorCmd } from './commands/cloud/doctor.ts';
import type { command as cloudNangoCmd } from './commands/cloud/nango.ts';
import type { command as cloudNangoIntegrationsAddCmd } from './commands/cloud/nango/integrations/add.ts';
import type { command as cloudNangoIntegrationsCmd } from './commands/cloud/nango/integrations.ts';
import type { command as cloudNangoIntegrationsDeployCmd } from './commands/cloud/nango/integrations/deploy.ts';
import type { command as cloudNangoIntegrationsStatusCmd } from './commands/cloud/nango/integrations/status.ts';
import type { command as cloudNangoRestoreCmd } from './commands/cloud/nango/restore.ts';
import type { command as cloudOpenCmd } from './commands/cloud/open.ts';
import type { command as cloudRecoverCmd } from './commands/cloud/recover.ts';
import type { command as cloudRestoreCmd } from './commands/cloud/restore.ts';
import type { command as cloudResumeCmd } from './commands/cloud/resume.ts';
import type { command as cloudSetupCmd } from './commands/cloud/setup.ts';
import type { command as cloudStatusCmd } from './commands/cloud/status.ts';
import type { command as cloudTemplateApplyCmd } from './commands/cloud/template/apply.ts';
import type { command as cloudTemplateCmd } from './commands/cloud/template.ts';
import type { command as cloudTemplatePlanCmd } from './commands/cloud/template/plan.ts';
import type { command as cloudUpdateCmd } from './commands/cloud/update.ts';
import type { command as localCmd } from './commands/local.ts';
import type { command as localDestroyCmd } from './commands/local/destroy.ts';
import type { command as localDoctorCmd } from './commands/local/doctor.ts';
import type { command as localNangoCmd } from './commands/local/nango.ts';
import type { command as localOpenCmd } from './commands/local/open.ts';
import type { command as localSetupCmd } from './commands/local/setup.ts';
import type { command as localStatusCmd } from './commands/local/status.ts';
import type { command as localTemplateApplyCmd } from './commands/local/template/apply.ts';
import type { command as localTemplateCmd } from './commands/local/template.ts';
import type { command as localTemplatePlanCmd } from './commands/local/template/plan.ts';
import type { command as localUpdateCmd } from './commands/local/update.ts';
import type { command as rootCmd } from './commands/_root.ts';
import type { command as updateCmd } from './commands/update.ts';
import type { command as versionCmd } from './commands/version.ts';

declare module '@parshjs/core' {
  interface CommandRegistry {
    'agent-sync': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'agent-sync install': {
      parents: {
        'agent-sync': { options: InferForwardedOptions<typeof agentsyncCmd.options>; params: InferParams<typeof agentsyncCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'agent-sync status': {
      parents: {
        'agent-sync': { options: InferForwardedOptions<typeof agentsyncCmd.options>; params: InferParams<typeof agentsyncCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'agent-sync sync-now': {
      parents: {
        'agent-sync': { options: InferForwardedOptions<typeof agentsyncCmd.options>; params: InferParams<typeof agentsyncCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'agent-sync uninstall': {
      parents: {
        'agent-sync': { options: InferForwardedOptions<typeof agentsyncCmd.options>; params: InferParams<typeof agentsyncCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud backup': {
      parents: {
        'cloud': { options: InferForwardedOptions<typeof cloudCmd.options>; params: InferParams<typeof cloudCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud destroy': {
      parents: {
        'cloud': { options: InferForwardedOptions<typeof cloudCmd.options>; params: InferParams<typeof cloudCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud doctor': {
      parents: {
        'cloud': { options: InferForwardedOptions<typeof cloudCmd.options>; params: InferParams<typeof cloudCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud nango': {
      parents: {
        'cloud': { options: InferForwardedOptions<typeof cloudCmd.options>; params: InferParams<typeof cloudCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud nango integrations': {
      parents: {
        'cloud': { options: InferForwardedOptions<typeof cloudCmd.options>; params: InferParams<typeof cloudCmd.params> };
        'cloud nango': { options: InferForwardedOptions<typeof cloudNangoCmd.options>; params: InferParams<typeof cloudNangoCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud nango integrations add': {
      parents: {
        'cloud': { options: InferForwardedOptions<typeof cloudCmd.options>; params: InferParams<typeof cloudCmd.params> };
        'cloud nango': { options: InferForwardedOptions<typeof cloudNangoCmd.options>; params: InferParams<typeof cloudNangoCmd.params> };
        'cloud nango integrations': { options: InferForwardedOptions<typeof cloudNangoIntegrationsCmd.options>; params: InferParams<typeof cloudNangoIntegrationsCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud nango integrations deploy': {
      parents: {
        'cloud': { options: InferForwardedOptions<typeof cloudCmd.options>; params: InferParams<typeof cloudCmd.params> };
        'cloud nango': { options: InferForwardedOptions<typeof cloudNangoCmd.options>; params: InferParams<typeof cloudNangoCmd.params> };
        'cloud nango integrations': { options: InferForwardedOptions<typeof cloudNangoIntegrationsCmd.options>; params: InferParams<typeof cloudNangoIntegrationsCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud nango integrations status': {
      parents: {
        'cloud': { options: InferForwardedOptions<typeof cloudCmd.options>; params: InferParams<typeof cloudCmd.params> };
        'cloud nango': { options: InferForwardedOptions<typeof cloudNangoCmd.options>; params: InferParams<typeof cloudNangoCmd.params> };
        'cloud nango integrations': { options: InferForwardedOptions<typeof cloudNangoIntegrationsCmd.options>; params: InferParams<typeof cloudNangoIntegrationsCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud nango restore': {
      parents: {
        'cloud': { options: InferForwardedOptions<typeof cloudCmd.options>; params: InferParams<typeof cloudCmd.params> };
        'cloud nango': { options: InferForwardedOptions<typeof cloudNangoCmd.options>; params: InferParams<typeof cloudNangoCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud open': {
      parents: {
        'cloud': { options: InferForwardedOptions<typeof cloudCmd.options>; params: InferParams<typeof cloudCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud recover': {
      parents: {
        'cloud': { options: InferForwardedOptions<typeof cloudCmd.options>; params: InferParams<typeof cloudCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud restore': {
      parents: {
        'cloud': { options: InferForwardedOptions<typeof cloudCmd.options>; params: InferParams<typeof cloudCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud resume': {
      parents: {
        'cloud': { options: InferForwardedOptions<typeof cloudCmd.options>; params: InferParams<typeof cloudCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud setup': {
      parents: {
        'cloud': { options: InferForwardedOptions<typeof cloudCmd.options>; params: InferParams<typeof cloudCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud status': {
      parents: {
        'cloud': { options: InferForwardedOptions<typeof cloudCmd.options>; params: InferParams<typeof cloudCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud template': {
      parents: {
        'cloud': { options: InferForwardedOptions<typeof cloudCmd.options>; params: InferParams<typeof cloudCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud template apply': {
      parents: {
        'cloud': { options: InferForwardedOptions<typeof cloudCmd.options>; params: InferParams<typeof cloudCmd.params> };
        'cloud template': { options: InferForwardedOptions<typeof cloudTemplateCmd.options>; params: InferParams<typeof cloudTemplateCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud template plan': {
      parents: {
        'cloud': { options: InferForwardedOptions<typeof cloudCmd.options>; params: InferParams<typeof cloudCmd.params> };
        'cloud template': { options: InferForwardedOptions<typeof cloudTemplateCmd.options>; params: InferParams<typeof cloudTemplateCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'cloud update': {
      parents: {
        'cloud': { options: InferForwardedOptions<typeof cloudCmd.options>; params: InferParams<typeof cloudCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local destroy': {
      parents: {
        'local': { options: InferForwardedOptions<typeof localCmd.options>; params: InferParams<typeof localCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local doctor': {
      parents: {
        'local': { options: InferForwardedOptions<typeof localCmd.options>; params: InferParams<typeof localCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local nango': {
      parents: {
        'local': { options: InferForwardedOptions<typeof localCmd.options>; params: InferParams<typeof localCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local open': {
      parents: {
        'local': { options: InferForwardedOptions<typeof localCmd.options>; params: InferParams<typeof localCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local setup': {
      parents: {
        'local': { options: InferForwardedOptions<typeof localCmd.options>; params: InferParams<typeof localCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local status': {
      parents: {
        'local': { options: InferForwardedOptions<typeof localCmd.options>; params: InferParams<typeof localCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local template': {
      parents: {
        'local': { options: InferForwardedOptions<typeof localCmd.options>; params: InferParams<typeof localCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local template apply': {
      parents: {
        'local': { options: InferForwardedOptions<typeof localCmd.options>; params: InferParams<typeof localCmd.params> };
        'local template': { options: InferForwardedOptions<typeof localTemplateCmd.options>; params: InferParams<typeof localTemplateCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local template plan': {
      parents: {
        'local': { options: InferForwardedOptions<typeof localCmd.options>; params: InferParams<typeof localCmd.params> };
        'local template': { options: InferForwardedOptions<typeof localTemplateCmd.options>; params: InferParams<typeof localTemplateCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'local update': {
      parents: {
        'local': { options: InferForwardedOptions<typeof localCmd.options>; params: InferParams<typeof localCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'update': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'version': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: { path: '', load: () => import('./commands/_root.ts').then((m) => m.command) },
  literalChildren: {
    'agent-sync': {
      segment: { kind: 'literal', value: 'agent-sync' },
      command: { path: 'agent-sync', load: () => import('./commands/agent-sync.ts').then((m) => m.command) },
      literalChildren: {
        'install': {
          segment: { kind: 'literal', value: 'install' },
          command: { path: 'agent-sync install', load: () => import('./commands/agent-sync/install.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'status': {
          segment: { kind: 'literal', value: 'status' },
          command: { path: 'agent-sync status', load: () => import('./commands/agent-sync/status.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'sync-now': {
          segment: { kind: 'literal', value: 'sync-now' },
          command: { path: 'agent-sync sync-now', load: () => import('./commands/agent-sync/sync-now.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'uninstall': {
          segment: { kind: 'literal', value: 'uninstall' },
          command: { path: 'agent-sync uninstall', load: () => import('./commands/agent-sync/uninstall.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
      },
      paramChild: null,
    },
    'cloud': {
      segment: { kind: 'literal', value: 'cloud' },
      command: { path: 'cloud', load: () => import('./commands/cloud.ts').then((m) => m.command) },
      literalChildren: {
        'backup': {
          segment: { kind: 'literal', value: 'backup' },
          command: { path: 'cloud backup', load: () => import('./commands/cloud/backup.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'destroy': {
          segment: { kind: 'literal', value: 'destroy' },
          command: { path: 'cloud destroy', load: () => import('./commands/cloud/destroy.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'doctor': {
          segment: { kind: 'literal', value: 'doctor' },
          command: { path: 'cloud doctor', load: () => import('./commands/cloud/doctor.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'nango': {
          segment: { kind: 'literal', value: 'nango' },
          command: { path: 'cloud nango', load: () => import('./commands/cloud/nango.ts').then((m) => m.command) },
          literalChildren: {
            'integrations': {
              segment: { kind: 'literal', value: 'integrations' },
              command: { path: 'cloud nango integrations', load: () => import('./commands/cloud/nango/integrations.ts').then((m) => m.command) },
              literalChildren: {
                'add': {
                  segment: { kind: 'literal', value: 'add' },
                  command: { path: 'cloud nango integrations add', load: () => import('./commands/cloud/nango/integrations/add.ts').then((m) => m.command) },
                  literalChildren: {},
                  paramChild: null,
                },
                'deploy': {
                  segment: { kind: 'literal', value: 'deploy' },
                  command: { path: 'cloud nango integrations deploy', load: () => import('./commands/cloud/nango/integrations/deploy.ts').then((m) => m.command) },
                  literalChildren: {},
                  paramChild: null,
                },
                'status': {
                  segment: { kind: 'literal', value: 'status' },
                  command: { path: 'cloud nango integrations status', load: () => import('./commands/cloud/nango/integrations/status.ts').then((m) => m.command) },
                  literalChildren: {},
                  paramChild: null,
                },
              },
              paramChild: null,
            },
            'restore': {
              segment: { kind: 'literal', value: 'restore' },
              command: { path: 'cloud nango restore', load: () => import('./commands/cloud/nango/restore.ts').then((m) => m.command) },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
        'open': {
          segment: { kind: 'literal', value: 'open' },
          command: { path: 'cloud open', load: () => import('./commands/cloud/open.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'recover': {
          segment: { kind: 'literal', value: 'recover' },
          command: { path: 'cloud recover', load: () => import('./commands/cloud/recover.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'restore': {
          segment: { kind: 'literal', value: 'restore' },
          command: { path: 'cloud restore', load: () => import('./commands/cloud/restore.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'resume': {
          segment: { kind: 'literal', value: 'resume' },
          command: { path: 'cloud resume', load: () => import('./commands/cloud/resume.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'setup': {
          segment: { kind: 'literal', value: 'setup' },
          command: { path: 'cloud setup', load: () => import('./commands/cloud/setup.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'status': {
          segment: { kind: 'literal', value: 'status' },
          command: { path: 'cloud status', load: () => import('./commands/cloud/status.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'template': {
          segment: { kind: 'literal', value: 'template' },
          command: { path: 'cloud template', load: () => import('./commands/cloud/template.ts').then((m) => m.command) },
          literalChildren: {
            'apply': {
              segment: { kind: 'literal', value: 'apply' },
              command: { path: 'cloud template apply', load: () => import('./commands/cloud/template/apply.ts').then((m) => m.command) },
              literalChildren: {},
              paramChild: null,
            },
            'plan': {
              segment: { kind: 'literal', value: 'plan' },
              command: { path: 'cloud template plan', load: () => import('./commands/cloud/template/plan.ts').then((m) => m.command) },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
        'update': {
          segment: { kind: 'literal', value: 'update' },
          command: { path: 'cloud update', load: () => import('./commands/cloud/update.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
      },
      paramChild: null,
    },
    'local': {
      segment: { kind: 'literal', value: 'local' },
      command: { path: 'local', load: () => import('./commands/local.ts').then((m) => m.command) },
      literalChildren: {
        'destroy': {
          segment: { kind: 'literal', value: 'destroy' },
          command: { path: 'local destroy', load: () => import('./commands/local/destroy.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'doctor': {
          segment: { kind: 'literal', value: 'doctor' },
          command: { path: 'local doctor', load: () => import('./commands/local/doctor.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'nango': {
          segment: { kind: 'literal', value: 'nango' },
          command: { path: 'local nango', load: () => import('./commands/local/nango.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'open': {
          segment: { kind: 'literal', value: 'open' },
          command: { path: 'local open', load: () => import('./commands/local/open.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'setup': {
          segment: { kind: 'literal', value: 'setup' },
          command: { path: 'local setup', load: () => import('./commands/local/setup.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'status': {
          segment: { kind: 'literal', value: 'status' },
          command: { path: 'local status', load: () => import('./commands/local/status.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'template': {
          segment: { kind: 'literal', value: 'template' },
          command: { path: 'local template', load: () => import('./commands/local/template.ts').then((m) => m.command) },
          literalChildren: {
            'apply': {
              segment: { kind: 'literal', value: 'apply' },
              command: { path: 'local template apply', load: () => import('./commands/local/template/apply.ts').then((m) => m.command) },
              literalChildren: {},
              paramChild: null,
            },
            'plan': {
              segment: { kind: 'literal', value: 'plan' },
              command: { path: 'local template plan', load: () => import('./commands/local/template/plan.ts').then((m) => m.command) },
              literalChildren: {},
              paramChild: null,
            },
          },
          paramChild: null,
        },
        'update': {
          segment: { kind: 'literal', value: 'update' },
          command: { path: 'local update', load: () => import('./commands/local/update.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
      },
      paramChild: null,
    },
    'update': {
      segment: { kind: 'literal', value: 'update' },
      command: { path: 'update', load: () => import('./commands/update.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'version': {
      segment: { kind: 'literal', value: 'version' },
      command: { path: 'version', load: () => import('./commands/version.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
  },
  paramChild: null,
};
