/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen - do not edit by hand.
import type { InferForwardedOptions, InferParams, RuntimeNode } from '@parshjs/core';
import type { command as backupCmd } from './commands/backup.ts';
import type { command as destroyCmd } from './commands/destroy.ts';
import type { command as doctorCmd } from './commands/doctor.ts';
import type { command as openCmd } from './commands/open.ts';
import type { command as recoverCmd } from './commands/recover.ts';
import type { command as restoreCmd } from './commands/restore.ts';
import type { command as resumeCmd } from './commands/resume.ts';
import type { command as rootCmd } from './commands/_root.ts';
import type { command as setupCmd } from './commands/setup.ts';
import type { command as statusCmd } from './commands/status.ts';
import type { command as updateCmd } from './commands/update.ts';
import type { command as versionCmd } from './commands/version.ts';

declare module '@parshjs/core' {
  interface CommandRegistry {
    'backup': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'destroy': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'doctor': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'open': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'recover': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'restore': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'resume': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'setup': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'status': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'update': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'version': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: { path: '', load: () => import('./commands/_root.ts').then((m) => m.command) },
  literalChildren: {
    'backup': {
      segment: { kind: 'literal', value: 'backup' },
      command: { path: 'backup', load: () => import('./commands/backup.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'destroy': {
      segment: { kind: 'literal', value: 'destroy' },
      command: { path: 'destroy', load: () => import('./commands/destroy.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'doctor': {
      segment: { kind: 'literal', value: 'doctor' },
      command: { path: 'doctor', load: () => import('./commands/doctor.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'open': {
      segment: { kind: 'literal', value: 'open' },
      command: { path: 'open', load: () => import('./commands/open.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'recover': {
      segment: { kind: 'literal', value: 'recover' },
      command: { path: 'recover', load: () => import('./commands/recover.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'restore': {
      segment: { kind: 'literal', value: 'restore' },
      command: { path: 'restore', load: () => import('./commands/restore.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'resume': {
      segment: { kind: 'literal', value: 'resume' },
      command: { path: 'resume', load: () => import('./commands/resume.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'setup': {
      segment: { kind: 'literal', value: 'setup' },
      command: { path: 'setup', load: () => import('./commands/setup.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'status': {
      segment: { kind: 'literal', value: 'status' },
      command: { path: 'status', load: () => import('./commands/status.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'update': {
      segment: { kind: 'literal', value: 'update' },
      command: { path: 'update', load: () => import('./commands/update.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'version': {
      segment: { kind: 'literal', value: 'version' },
      command: { path: 'version', load: () => import('./commands/version.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
  },
  paramChild: null,
};
