import { expect, test } from "bun:test";
import {
  DEFAULT_APP_PORT,
  DEFAULT_NANGO_PORT,
  type LocalConfig,
  localAppOrigin,
  localComposeCommands,
  localNangoOrigin,
  localSetupUrl,
  normalizeLocalConfig,
  serializeRuntimeEnvironment,
} from "./local.ts";
import { nangoApiKeyWriteCommands } from "./nango.ts";
import { LOCAL_RUNTIME_SECRETS, RUNTIME_SECRET_LENGTHS } from "./runtime-secrets.ts";
import { localTarget } from "./target.ts";

const config: LocalConfig = {
  schemaVersion: 1,
  releaseVersion: "v0.1.69",
  ownerEmail: "owner@example.com",
  appPort: DEFAULT_APP_PORT,
  nangoPort: DEFAULT_NANGO_PORT,
};

const target = localTarget({
  origin: localAppOrigin(config),
  deployDirectory: "/home/owner/.cache/context-use/releases/v0.1.69/deploy",
  runtimeEnvPath: "/home/owner/.config/context-use/local/runtime.env",
});

test("a local installation is addressed on loopback", () => {
  expect(localAppOrigin(config)).toBe("http://localhost:5173");
  expect(localNangoOrigin(config)).toBe("http://localhost:5174");
  expect(localSetupUrl(config, "token/value")).toBe("http://localhost:5173/app#setup=token%2Fvalue");
});

test("local config rejects values that would produce an unusable installation", () => {
  expect(() => normalizeLocalConfig({ ...config, ownerEmail: "not-an-email" })).toThrow("invalid owner email");
  expect(() => normalizeLocalConfig({ ...config, releaseVersion: "latest" })).toThrow("invalid release version");
  expect(() => normalizeLocalConfig({ ...config, appPort: 80 })).toThrow("invalid port");
  expect(() => normalizeLocalConfig({ ...config, nangoPort: DEFAULT_APP_PORT })).toThrow("one port for two services");
  expect(normalizeLocalConfig(config)).toEqual(config);
});

test("compose runs against the released local file inside the verified deployment bundle", () => {
  expect(localComposeCommands(target, "up", "-d", "--wait")).toEqual([
    "set -euo pipefail",
    "cd '/home/owner/.cache/context-use/releases/v0.1.69/deploy'",
    "docker compose --env-file '/home/owner/.config/context-use/local/runtime.env' --file compose.local.yml up -d --wait",
  ]);
});

test("a runtime value that spans lines is refused rather than silently truncating the environment", () => {
  expect(() => serializeRuntimeEnvironment({ A: "one\ntwo" })).toThrow("spans multiple lines");
  expect(serializeRuntimeEnvironment({ A: "1", B: "2" })).toBe("A=1\nB=2\n");
});

test("the shared Nango key worker is reused locally and refuses an unmanaged key", () => {
  const commands = nangoApiKeyWriteCommands({
    deployDirectory: target.deployDirectory,
    compose: "docker compose --file compose.local.yml",
    displayName: "context-use-pipeline",
  });
  expect(commands[0]).toBe("cd '/home/owner/.cache/context-use/releases/v0.1.69/deploy'");
  expect(commands.at(-1)).toContain("CONTEXT_USE_MANAGED_KEY='context-use-pipeline'");
  expect(commands.at(-1)).toContain("CONTEXT_USE_KEY_MODE=write");
  expect(() => nangoApiKeyWriteCommands({
    deployDirectory: target.deployDirectory,
    compose: "docker compose",
    displayName: "context-use-admin",
  })).toThrow("Unknown managed Nango API key");
});

test("every credential the local Compose file interpolates is generated by the local secret set", async () => {
  const compose = await Bun.file(new URL("../../../deploy/compose.local.yml", import.meta.url)).text();
  // Values the installer writes directly rather than generating as secrets.
  const provided = new Set([
    "APP_IMAGE",
    "BACKUP_IMAGE",
    "NANGO_IMAGE",
    "APP_ORIGIN",
    "NANGO_ORIGIN",
    "APP_PORT",
    "NANGO_PORT",
    "OWNER_EMAIL",
    "NANGO_DASHBOARD_USERNAME",
    "OWNER_SETUP_TOKEN_HASH",
    ...LOCAL_RUNTIME_SECRETS,
  ]);
  const referenced = new Set<string>();
  for (const match of compose.matchAll(/\$\{([A-Z0-9_]+)(:-[^}]*)?\}/g)) {
    // `${NAME:-}` declares its own fallback; those are reconciled after the
    // stack is running, like the Nango pipeline key.
    if (!match[2]) referenced.add(match[1]!);
  }
  expect(referenced.size).toBeGreaterThan(0);
  expect([...referenced].filter((name) => !provided.has(name))).toEqual([]);
});

test("the local secret set omits only the credentials belonging to the cloud Nango edge", () => {
  const omitted = (Object.keys(RUNTIME_SECRET_LENGTHS) as Array<keyof typeof RUNTIME_SECRET_LENGTHS>)
    .filter((name) => !LOCAL_RUNTIME_SECRETS.includes(name));
  expect(omitted).toEqual([
    "NANGO_OAUTH_CLIENT_ID",
    "NANGO_OAUTH_CLIENT_SECRET",
    "NANGO_AUTH_COOKIE_SECRET",
    "AUTH_NANGO_TOKEN",
  ]);
});
